/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package controlador;

/**
 *
 * @author eldoc
 */
/*
 * ventanaGrafica.java
 *
 * Created on 9 de agosto de 2003, 9:11
 */
import java.awt.image.*;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.xy.XYSeries;
import org.jfree.data.xy.XYSeriesCollection;

/**
 *
 * @author Roberto Canales
 */
public class ventanaGrafica extends java.awt.Frame {

    BufferedImage grafica = null;

    /**
     * Creates new form ventanaGrafica
     */
    public ventanaGrafica() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void initComponents() {

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        pack();
    }

    /**
     * Exit the Application
     */
    private void exitForm(java.awt.event.WindowEvent evt) {
        System.exit(0);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        ventanaGrafica miventana = new ventanaGrafica();
        miventana.setSize(400, 400);
        miventana.show();
    }

    public BufferedImage creaImagen() {
        XYSeries series = new XYSeries("Evolucion");
        series.add(1, 23);
        series.add(2, 34);
        series.add(3, 51);
        series.add(4, 67);
        series.add(5, 89);
        series.add(6, 121);
        series.add(7, 137);
        XYSeriesCollection juegoDatos = new XYSeriesCollection(series);

        JFreeChart chart
                = ChartFactory.createXYLineChart("Sesiones en Adictos al Trabajo",
                        "Meses", "Sesiones", juegoDatos, PlotOrientation.VERTICAL,
                        false,
                        false,
                        true // Show legend
                );

        BufferedImage image = chart.createBufferedImage(300, 300);
        return image;
    }

    public void paint(java.awt.Graphics g) {
        //super.paint(g);

        if (grafica == null) {
            grafica = this.creaImagen();
        }
        g.drawImage(grafica, 30, 30, null);
    }

}
