/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.miFiltro;
import controlador.progresBar;
import java.awt.Component;
import java.awt.Container;
import java.awt.HeadlessException;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.ArrayList;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.UIManager;
import modelo.madalineDCO;
import modelo.madalineTCO;
import modelo.madalineUCO;

/**
 *
 * @author proxc
 */
public class FrmCrearArchivo extends javax.swing.JFrame {

    /**
     * Creates new form Home_Data
     */
    private int m;
    private int columnas;
    private int filas;
    private double[][] x;
    private double[][] yd;
    madalineDCO md2;
    madalineUCO md1;
    madalineTCO md3;
    Thread hilo;
    Thread hiloProgresBar;
    progresBar pg;
    public static boolean band = true;
    double[][] matE;
    int fil;
    int col;

    public FrmCrearArchivo() {
        initComponents();
        Animacion.Animacion.mover_izquierda(0, -264, 2, 2, panelMenuMinimizado);
        btnGuardar.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fileChooser = new javax.swing.JFileChooser();
        jLabel1 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        panelCuerpo = new javax.swing.JPanel();
        paneTitulo = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        panelIconoMenu = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        panelMenu = new MaterialSwing.MaterialButtomPanel();
        jLabel23 = new javax.swing.JLabel();
        panelMenuMinimizado = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        btnInicioXs = new MaterialSwing.MaterialButtomPanel();
        jLabel27 = new javax.swing.JLabel();
        btnMadalineLg1 = new MaterialSwing.MaterialButtomPanel();
        jLabel28 = new javax.swing.JLabel();
        btnPerceptronLg1 = new MaterialSwing.MaterialButtomPanel();
        jLabel43 = new javax.swing.JLabel();
        btnSimularLg1 = new MaterialSwing.MaterialButtomPanel();
        jLabel33 = new javax.swing.JLabel();
        btnCrearLg1 = new MaterialSwing.MaterialButtomPanel();
        jLabel35 = new javax.swing.JLabel();
        btnVerRegistrosLg1 = new MaterialSwing.MaterialButtomPanel();
        jLabel44 = new javax.swing.JLabel();
        btnSalirLg1 = new MaterialSwing.MaterialButtomPanel();
        jLabel45 = new javax.swing.JLabel();
        panelCardLayout = new javax.swing.JPanel();
        materialButtomPanel2 = new MaterialSwing.MaterialButtomPanel();
        jLabel4 = new javax.swing.JLabel();
        lblNumeroEntradas1 = new javax.swing.JLabel();
        lblNumeroEntradas = new javax.swing.JLabel();
        lblNumeroPatrones1 = new javax.swing.JLabel();
        lblNumeroPatrones = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        txtFilas = new MaterialSwing.MaterialTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtColumnas = new MaterialSwing.MaterialTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        btnGuardar = new MaterialSwing.MaterialButtomPanel();
        jLabel6 = new javax.swing.JLabel();
        btnGuardarComo = new MaterialSwing.MaterialButtomPanel();
        jLabel7 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        jLabel37.setText("jLabel37");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                formMouseMoved(evt);
            }
        });

        panelCuerpo.setBackground(new java.awt.Color(255, 255, 255));
        panelCuerpo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        paneTitulo.setBackground(new java.awt.Color(255, 255, 255));
        org.jdesktop.swingx.border.DropShadowBorder dropShadowBorder1 = new org.jdesktop.swingx.border.DropShadowBorder();
        dropShadowBorder1.setShadowSize(10);
        dropShadowBorder1.setShowRightShadow(false);
        paneTitulo.setBorder(dropShadowBorder1);

        jPanel5.setBackground(new java.awt.Color(139, 195, 74));

        jLabel15.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/images/icons8_Edit_Property_48px_2.png"))); // NOI18N
        jLabel15.setText("Crear Archivo");

        jPanel1.setBackground(new java.awt.Color(104, 159, 56));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 18, Short.MAX_VALUE)
        );

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/images/logo U.png"))); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 569, Short.MAX_VALUE)
                .addComponent(jLabel21)
                .addGap(28, 28, 28))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel21)
                    .addComponent(jLabel15))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout paneTituloLayout = new javax.swing.GroupLayout(paneTitulo);
        paneTitulo.setLayout(paneTituloLayout);
        paneTituloLayout.setHorizontalGroup(
            paneTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneTituloLayout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        paneTituloLayout.setVerticalGroup(
            paneTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        panelCuerpo.add(paneTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 140));

        panelIconoMenu.setBackground(new java.awt.Color(255, 255, 255));
        org.jdesktop.swingx.border.DropShadowBorder dropShadowBorder2 = new org.jdesktop.swingx.border.DropShadowBorder();
        dropShadowBorder2.setShadowSize(10);
        panelIconoMenu.setBorder(dropShadowBorder2);

        jPanel6.setBackground(new java.awt.Color(94, 94, 95));
        jPanel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel6MouseClicked(evt);
            }
        });

        panelMenu.setBackground(new java.awt.Color(94, 94, 95));
        panelMenu.setPreferredSize(new java.awt.Dimension(53, 40));
        panelMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelMenuMouseClicked(evt);
            }
        });

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/images/icons8_Menu_24px.png"))); // NOI18N
        jLabel23.setMaximumSize(new java.awt.Dimension(32, 32));
        jLabel23.setMinimumSize(new java.awt.Dimension(32, 32));
        jLabel23.setName(""); // NOI18N
        jLabel23.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout panelMenuLayout = new javax.swing.GroupLayout(panelMenu);
        panelMenu.setLayout(panelMenuLayout);
        panelMenuLayout.setHorizontalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelMenuLayout.setVerticalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuLayout.createSequentialGroup()
                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 10, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 53, Short.MAX_VALUE)
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addComponent(panelMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 34, Short.MAX_VALUE)
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addComponent(panelMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 12, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout panelIconoMenuLayout = new javax.swing.GroupLayout(panelIconoMenu);
        panelIconoMenu.setLayout(panelIconoMenuLayout);
        panelIconoMenuLayout.setHorizontalGroup(
            panelIconoMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelIconoMenuLayout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelIconoMenuLayout.setVerticalGroup(
            panelIconoMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelIconoMenuLayout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelCuerpo.add(panelIconoMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 60, 40));

        panelMenuMinimizado.setBackground(new java.awt.Color(255, 255, 255));
        org.jdesktop.swingx.border.DropShadowBorder dropShadowBorder3 = new org.jdesktop.swingx.border.DropShadowBorder();
        dropShadowBorder3.setShadowSize(10);
        panelMenuMinimizado.setBorder(dropShadowBorder3);

        jPanel3.setBackground(new java.awt.Color(94, 94, 95));

        btnInicioXs.setBackground(new java.awt.Color(94, 94, 95));
        btnInicioXs.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        btnInicioXs.setPreferredSize(new java.awt.Dimension(53, 40));
        btnInicioXs.setRippleColor(new java.awt.Color(51, 204, 0));
        btnInicioXs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnInicioXsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnInicioXsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnInicioXsMouseExited(evt);
            }
        });

        jLabel27.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 12)); // NOI18N
        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/images/icons8_Home_24px_2.png"))); // NOI18N
        jLabel27.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jLabel27.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel27MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout btnInicioXsLayout = new javax.swing.GroupLayout(btnInicioXs);
        btnInicioXs.setLayout(btnInicioXsLayout);
        btnInicioXsLayout.setHorizontalGroup(
            btnInicioXsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnInicioXsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btnInicioXsLayout.setVerticalGroup(
            btnInicioXsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnInicioXsLayout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(jLabel27)
                .addContainerGap())
        );

        btnMadalineLg1.setBackground(new java.awt.Color(94, 94, 95));
        btnMadalineLg1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        btnMadalineLg1.setPreferredSize(new java.awt.Dimension(53, 40));
        btnMadalineLg1.setRippleColor(new java.awt.Color(51, 204, 0));
        btnMadalineLg1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMadalineLg1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMadalineLg1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMadalineLg1MouseExited(evt);
            }
        });

        jLabel28.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/images/icons8_Brain_24px.png"))); // NOI18N
        jLabel28.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout btnMadalineLg1Layout = new javax.swing.GroupLayout(btnMadalineLg1);
        btnMadalineLg1.setLayout(btnMadalineLg1Layout);
        btnMadalineLg1Layout.setHorizontalGroup(
            btnMadalineLg1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnMadalineLg1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel28, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE))
        );
        btnMadalineLg1Layout.setVerticalGroup(
            btnMadalineLg1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnMadalineLg1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jLabel28)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        btnPerceptronLg1.setBackground(new java.awt.Color(94, 94, 95));
        btnPerceptronLg1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        btnPerceptronLg1.setPreferredSize(new java.awt.Dimension(53, 40));
        btnPerceptronLg1.setRippleColor(new java.awt.Color(51, 204, 0));
        btnPerceptronLg1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPerceptronLg1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnPerceptronLg1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnPerceptronLg1MouseExited(evt);
            }
        });

        jLabel43.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 12)); // NOI18N
        jLabel43.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/images/icons8_Google_Scholar_24px_2.png"))); // NOI18N
        jLabel43.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout btnPerceptronLg1Layout = new javax.swing.GroupLayout(btnPerceptronLg1);
        btnPerceptronLg1.setLayout(btnPerceptronLg1Layout);
        btnPerceptronLg1Layout.setHorizontalGroup(
            btnPerceptronLg1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnPerceptronLg1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel43, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btnPerceptronLg1Layout.setVerticalGroup(
            btnPerceptronLg1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnPerceptronLg1Layout.createSequentialGroup()
                .addComponent(jLabel43)
                .addGap(0, 12, Short.MAX_VALUE))
        );

        btnSimularLg1.setBackground(new java.awt.Color(94, 94, 95));
        btnSimularLg1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        btnSimularLg1.setPreferredSize(new java.awt.Dimension(53, 40));
        btnSimularLg1.setRippleColor(new java.awt.Color(51, 204, 0));
        btnSimularLg1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSimularLg1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSimularLg1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSimularLg1MouseExited(evt);
            }
        });

        jLabel33.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 12)); // NOI18N
        jLabel33.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/images/icons8_HIPS_24px_2.png"))); // NOI18N
        jLabel33.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout btnSimularLg1Layout = new javax.swing.GroupLayout(btnSimularLg1);
        btnSimularLg1.setLayout(btnSimularLg1Layout);
        btnSimularLg1Layout.setHorizontalGroup(
            btnSimularLg1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnSimularLg1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel33)
                .addGap(60, 60, 60))
        );
        btnSimularLg1Layout.setVerticalGroup(
            btnSimularLg1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnSimularLg1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jLabel33)
                .addGap(20, 20, 20))
        );

        btnCrearLg1.setBackground(new java.awt.Color(94, 94, 95));
        btnCrearLg1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        btnCrearLg1.setPreferredSize(new java.awt.Dimension(53, 40));
        btnCrearLg1.setRippleColor(new java.awt.Color(51, 204, 0));
        btnCrearLg1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCrearLg1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCrearLg1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCrearLg1MouseExited(evt);
            }
        });

        jLabel35.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 12)); // NOI18N
        jLabel35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/images/icons8_Edit_Property_24px.png"))); // NOI18N
        jLabel35.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout btnCrearLg1Layout = new javax.swing.GroupLayout(btnCrearLg1);
        btnCrearLg1.setLayout(btnCrearLg1Layout);
        btnCrearLg1Layout.setHorizontalGroup(
            btnCrearLg1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnCrearLg1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel35)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        btnCrearLg1Layout.setVerticalGroup(
            btnCrearLg1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnCrearLg1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jLabel35)
                .addContainerGap())
        );

        btnVerRegistrosLg1.setBackground(new java.awt.Color(94, 94, 95));
        btnVerRegistrosLg1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        btnVerRegistrosLg1.setPreferredSize(new java.awt.Dimension(53, 40));
        btnVerRegistrosLg1.setRippleColor(new java.awt.Color(51, 204, 0));
        btnVerRegistrosLg1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVerRegistrosLg1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnVerRegistrosLg1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnVerRegistrosLg1MouseExited(evt);
            }
        });

        jLabel44.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 12)); // NOI18N
        jLabel44.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/images/icons8_Search_Property_24px_1.png"))); // NOI18N
        jLabel44.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout btnVerRegistrosLg1Layout = new javax.swing.GroupLayout(btnVerRegistrosLg1);
        btnVerRegistrosLg1.setLayout(btnVerRegistrosLg1Layout);
        btnVerRegistrosLg1Layout.setHorizontalGroup(
            btnVerRegistrosLg1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnVerRegistrosLg1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel44, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE))
        );
        btnVerRegistrosLg1Layout.setVerticalGroup(
            btnVerRegistrosLg1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnVerRegistrosLg1Layout.createSequentialGroup()
                .addComponent(jLabel44)
                .addGap(0, 12, Short.MAX_VALUE))
        );

        btnSalirLg1.setBackground(new java.awt.Color(94, 94, 95));
        btnSalirLg1.setPreferredSize(new java.awt.Dimension(53, 43));
        btnSalirLg1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSalirLg1MouseClicked(evt);
            }
        });

        jLabel45.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/images/icons8_Exit_Sign_24px_3.png"))); // NOI18N

        javax.swing.GroupLayout btnSalirLg1Layout = new javax.swing.GroupLayout(btnSalirLg1);
        btnSalirLg1.setLayout(btnSalirLg1Layout);
        btnSalirLg1Layout.setHorizontalGroup(
            btnSalirLg1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnSalirLg1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel45, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(19, 19, 19))
        );
        btnSalirLg1Layout.setVerticalGroup(
            btnSalirLg1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnSalirLg1Layout.createSequentialGroup()
                .addComponent(jLabel45, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnPerceptronLg1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btnSimularLg1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btnCrearLg1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btnMadalineLg1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btnInicioXs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btnVerRegistrosLg1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btnSalirLg1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(btnInicioXs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnMadalineLg1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnPerceptronLg1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnSimularLg1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnCrearLg1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnVerRegistrosLg1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSalirLg1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout panelMenuMinimizadoLayout = new javax.swing.GroupLayout(panelMenuMinimizado);
        panelMenuMinimizado.setLayout(panelMenuMinimizadoLayout);
        panelMenuMinimizadoLayout.setHorizontalGroup(
            panelMenuMinimizadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuMinimizadoLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelMenuMinimizadoLayout.setVerticalGroup(
            panelMenuMinimizadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        panelCuerpo.add(panelMenuMinimizado, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 60, 360));

        panelCardLayout.setBackground(new java.awt.Color(255, 255, 255));
        org.jdesktop.swingx.border.DropShadowBorder dropShadowBorder4 = new org.jdesktop.swingx.border.DropShadowBorder();
        dropShadowBorder4.setShowLeftShadow(true);
        dropShadowBorder4.setShowTopShadow(true);
        panelCardLayout.setBorder(dropShadowBorder4);

        materialButtomPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                materialButtomPanel2MouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 11)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/images/icons8_Open_24px_2.png"))); // NOI18N
        jLabel4.setText("Editar Archivo");

        javax.swing.GroupLayout materialButtomPanel2Layout = new javax.swing.GroupLayout(materialButtomPanel2);
        materialButtomPanel2.setLayout(materialButtomPanel2Layout);
        materialButtomPanel2Layout.setHorizontalGroup(
            materialButtomPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(materialButtomPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(28, Short.MAX_VALUE))
        );
        materialButtomPanel2Layout.setVerticalGroup(
            materialButtomPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(materialButtomPanel2Layout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                .addContainerGap())
        );

        lblNumeroEntradas1.setBackground(javax.swing.UIManager.getDefaults().getColor("window"));
        lblNumeroEntradas1.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 12)); // NOI18N
        lblNumeroEntradas1.setForeground(new java.awt.Color(51, 51, 51));
        lblNumeroEntradas1.setText("Columnas");

        lblNumeroEntradas.setBackground(javax.swing.UIManager.getDefaults().getColor("window"));
        lblNumeroEntradas.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 12)); // NOI18N
        lblNumeroEntradas.setForeground(new java.awt.Color(51, 51, 51));
        lblNumeroEntradas.setText("0");

        lblNumeroPatrones1.setBackground(javax.swing.UIManager.getDefaults().getColor("window"));
        lblNumeroPatrones1.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 12)); // NOI18N
        lblNumeroPatrones1.setForeground(new java.awt.Color(51, 51, 51));
        lblNumeroPatrones1.setText("Filas");

        lblNumeroPatrones.setBackground(javax.swing.UIManager.getDefaults().getColor("window"));
        lblNumeroPatrones.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 12)); // NOI18N
        lblNumeroPatrones.setForeground(new java.awt.Color(51, 51, 51));
        lblNumeroPatrones.setText("0");

        jLabel2.setText("Filas");

        jLabel5.setText("Columnas");

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tabla.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        tabla.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                tablaInputMethodTextChanged(evt);
            }
        });
        jScrollPane1.setViewportView(tabla);

        txtFilas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtFilasKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFilasKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFilasKeyTyped(evt);
            }
        });

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/images/icons8_Sort_Down_20px.png"))); // NOI18N
        jLabel14.setPreferredSize(new java.awt.Dimension(20, 7));
        jLabel14.setRequestFocusEnabled(false);
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel14MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel14MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel14MouseExited(evt);
            }
        });

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/images/icons8_Sort_Up_20px.png"))); // NOI18N
        jLabel11.setPreferredSize(new java.awt.Dimension(20, 7));
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel11MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel11MouseExited(evt);
            }
        });

        txtColumnas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtColumnasKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtColumnasKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtColumnasKeyTyped(evt);
            }
        });

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/images/icons8_Sort_Down_20px.png"))); // NOI18N
        jLabel16.setPreferredSize(new java.awt.Dimension(20, 7));
        jLabel16.setRequestFocusEnabled(false);
        jLabel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel16MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel16MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel16MouseExited(evt);
            }
        });

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/images/icons8_Sort_Up_20px.png"))); // NOI18N
        jLabel12.setPreferredSize(new java.awt.Dimension(20, 7));
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel12MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel12MouseExited(evt);
            }
        });

        btnGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGuardarMouseClicked(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 11)); // NOI18N
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/images/icons8_Save_24px_1.png"))); // NOI18N
        jLabel6.setText("Guardar");

        javax.swing.GroupLayout btnGuardarLayout = new javax.swing.GroupLayout(btnGuardar);
        btnGuardar.setLayout(btnGuardarLayout);
        btnGuardarLayout.setHorizontalGroup(
            btnGuardarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnGuardarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addContainerGap(30, Short.MAX_VALUE))
        );
        btnGuardarLayout.setVerticalGroup(
            btnGuardarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnGuardarLayout.createSequentialGroup()
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnGuardarComo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGuardarComoMouseClicked(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 11)); // NOI18N
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/images/icons8_Save_as_24px.png"))); // NOI18N
        jLabel7.setText("Guardar Como");

        javax.swing.GroupLayout btnGuardarComoLayout = new javax.swing.GroupLayout(btnGuardarComo);
        btnGuardarComo.setLayout(btnGuardarComoLayout);
        btnGuardarComoLayout.setHorizontalGroup(
            btnGuardarComoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnGuardarComoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        btnGuardarComoLayout.setVerticalGroup(
            btnGuardarComoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnGuardarComoLayout.createSequentialGroup()
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout panelCardLayoutLayout = new javax.swing.GroupLayout(panelCardLayout);
        panelCardLayout.setLayout(panelCardLayoutLayout);
        panelCardLayoutLayout.setHorizontalGroup(
            panelCardLayoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCardLayoutLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(panelCardLayoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCardLayoutLayout.createSequentialGroup()
                        .addGroup(panelCardLayoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel2))
                        .addGap(20, 20, 20)
                        .addGroup(panelCardLayoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtFilas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtColumnas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelCardLayoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelCardLayoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelCardLayoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panelCardLayoutLayout.createSequentialGroup()
                        .addGroup(panelCardLayoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelCardLayoutLayout.createSequentialGroup()
                                .addComponent(materialButtomPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnGuardarComo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 646, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelCardLayoutLayout.createSequentialGroup()
                                .addComponent(lblNumeroEntradas1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblNumeroEntradas)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblNumeroPatrones1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblNumeroPatrones)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        panelCardLayoutLayout.setVerticalGroup(
            panelCardLayoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCardLayoutLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(panelCardLayoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelCardLayoutLayout.createSequentialGroup()
                        .addGroup(panelCardLayoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panelCardLayoutLayout.createSequentialGroup()
                                .addGroup(panelCardLayoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblNumeroEntradas)
                                    .addComponent(lblNumeroEntradas1)
                                    .addComponent(lblNumeroPatrones)
                                    .addComponent(lblNumeroPatrones1))
                                .addGap(18, 18, 18)
                                .addGroup(panelCardLayoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(txtFilas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(panelCardLayoutLayout.createSequentialGroup()
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(1, 1, 1)))
                        .addGap(10, 10, 10)
                        .addComponent(jLabel5))
                    .addComponent(txtColumnas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelCardLayoutLayout.createSequentialGroup()
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)))
                .addGap(18, 18, 18)
                .addGroup(panelCardLayoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(materialButtomPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnGuardarComo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(47, 47, 47)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                .addGap(26, 26, 26))
        );

        panelCuerpo.add(panelCardLayout, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 145, 740, 450));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelCuerpo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelCuerpo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInicioXsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInicioXsMouseClicked
        // TODO add your handling code here:
        new FrmInicio().setVisible(true);
    }//GEN-LAST:event_btnInicioXsMouseClicked

    private void btnInicioXsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInicioXsMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnInicioXsMouseEntered

    private void btnInicioXsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInicioXsMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnInicioXsMouseExited

    private void btnMadalineLg1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMadalineLg1MouseClicked
        // TODO add your handling code here:
        new FrmCrearArchivo().setVisible(true);
    }//GEN-LAST:event_btnMadalineLg1MouseClicked

    private void btnMadalineLg1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMadalineLg1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMadalineLg1MouseEntered

    private void btnMadalineLg1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMadalineLg1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMadalineLg1MouseExited

    private void btnPerceptronLg1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPerceptronLg1MouseClicked
        // TODO add your handling code here:
        new FrmPerceptron().setVisible(true);
    }//GEN-LAST:event_btnPerceptronLg1MouseClicked

    private void btnPerceptronLg1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPerceptronLg1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPerceptronLg1MouseEntered

    private void btnPerceptronLg1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPerceptronLg1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPerceptronLg1MouseExited

    private void btnSimularLg1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSimularLg1MouseClicked
        // TODO add your handling code here:
        new FrmSimular().setVisible(true);
    }//GEN-LAST:event_btnSimularLg1MouseClicked

    private void btnSimularLg1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSimularLg1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSimularLg1MouseEntered

    private void btnSimularLg1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSimularLg1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSimularLg1MouseExited

    private void btnCrearLg1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCrearLg1MouseClicked
        // TODO add your handling code here:
        new FrmCrearArchivo().setVisible(true);
    }//GEN-LAST:event_btnCrearLg1MouseClicked

    private void btnCrearLg1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCrearLg1MouseEntered
        // TODO add your handling code here:

    }//GEN-LAST:event_btnCrearLg1MouseEntered

    private void btnCrearLg1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCrearLg1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCrearLg1MouseExited

    private void btnVerRegistrosLg1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVerRegistrosLg1MouseClicked
        // TODO add your handling code here:
        new FrmConsultarArchivos().setVisible(true);
    }//GEN-LAST:event_btnVerRegistrosLg1MouseClicked

    private void btnVerRegistrosLg1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVerRegistrosLg1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVerRegistrosLg1MouseEntered

    private void btnVerRegistrosLg1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVerRegistrosLg1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVerRegistrosLg1MouseExited

    private void btnSalirLg1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirLg1MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnSalirLg1MouseClicked

    private void jLabel27MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel27MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel27MouseClicked

    private void panelMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelMenuMouseClicked
        // TODO add your handling code here:
        int posicion = panelMenuMinimizado.getX();
        if (posicion > -1) {
            Animacion.Animacion.mover_izquierda(0, -264, 2, 2, panelMenuMinimizado);
        } else {
            Animacion.Animacion.mover_derecha(-264, 0, 2, 2, panelMenuMinimizado);
        }
    }//GEN-LAST:event_panelMenuMouseClicked

    private void formMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseMoved
        // TODO add your handling code here:
        if (rootPaneCheckingEnabled) {

        }
    }//GEN-LAST:event_formMouseMoved

    private void jPanel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MouseClicked
        // TODO add your handling code here:
        int pos = this.panelIconoMenu.getX();
        if (pos < 0) {
            Animacion.Animacion.mover_derecha(0, -256, 3, 3, panelMenuMinimizado);
        } else {
            Animacion.Animacion.mover_izquierda(-256, 0, 3, 3, panelMenuMinimizado);
        }
    }//GEN-LAST:event_jPanel6MouseClicked

    private void materialButtomPanel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_materialButtomPanel2MouseClicked
        // TODO add your handling code here:
        abrirArchivo("Entradas");
    }//GEN-LAST:event_materialButtomPanel2MouseClicked

    private void tablaInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_tablaInputMethodTextChanged
        // TODO add your handling code here:

    }//GEN-LAST:event_tablaInputMethodTextChanged

    private void txtFilasKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFilasKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFilasKeyPressed

    private void txtFilasKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFilasKeyReleased
        // TODO add your handling code here:
        if (!txtFilas.getText().isEmpty()) {
            fil = (Integer.parseInt(txtFilas.getText()));
            System.out.println("numero de cap" + txtFilas.getText());
        }
    }//GEN-LAST:event_txtFilasKeyReleased

    private void txtFilasKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFilasKeyTyped
        // TODO add your handling code here:
        char caracter = evt.getKeyChar();
        // Verificar si la tecla pulsada no es un digito
        if (((caracter < '0') || (caracter > '9')) && (caracter != '\b' /*corresponde a BACK_SPACE*/)) {
            getToolkit().beep();
            evt.consume();  // ignorar el evento de teclado
            JOptionPane.showMessageDialog(null, "Ingresaste Un valor no valido", "valor no valido", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_txtFilasKeyTyped

    private void jLabel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseClicked
        // TODO add your handling code here:
        bajarNumero(txtFilas);
    }//GEN-LAST:event_jLabel14MouseClicked

    private void jLabel14MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel14MouseEntered

    private void jLabel14MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel14MouseExited

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        // TODO add your handling code here:
        subirNumero(txtFilas);
    }//GEN-LAST:event_jLabel11MouseClicked

    private void jLabel11MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel11MouseEntered

    private void jLabel11MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel11MouseExited

    private void txtColumnasKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtColumnasKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtColumnasKeyPressed

    private void txtColumnasKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtColumnasKeyReleased
        // TODO add your handling code here:
        if (!txtColumnas.getText().isEmpty()) {
            col = (Integer.parseInt(txtFilas.getText()));
            System.out.println("numero de cap" + txtFilas.getText());
            modelarTabla();
        }
    }//GEN-LAST:event_txtColumnasKeyReleased

    private void txtColumnasKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtColumnasKeyTyped
        // TODO add your handling code here:
        char caracter = evt.getKeyChar();
        // Verificar si la tecla pulsada no es un digito
        if (((caracter < '0') || (caracter > '9')) && (caracter != '\b' /*corresponde a BACK_SPACE*/)) {
            getToolkit().beep();
            evt.consume();  // ignorar el evento de teclado
            JOptionPane.showMessageDialog(null, "Ingresaste Un valor no valido", "valor no valido", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_txtColumnasKeyTyped

    private void jLabel16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseClicked
        // TODO add your handling code here:
        bajarNumero(txtColumnas);
    }//GEN-LAST:event_jLabel16MouseClicked

    private void jLabel16MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel16MouseEntered

    private void jLabel16MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel16MouseExited

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        // TODO add your handling code here:
        subirNumero(txtColumnas);
    }//GEN-LAST:event_jLabel12MouseClicked

    private void jLabel12MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel12MouseEntered

    private void jLabel12MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel12MouseExited

    private void btnGuardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarMouseClicked
        // TODO add your handling code here:
        guardarArchivo();
    }//GEN-LAST:event_btnGuardarMouseClicked

    private void btnGuardarComoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarComoMouseClicked
        // TODO add your handling code here:
        guardarArchivoComo();
    }//GEN-LAST:event_btnGuardarComoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmCrearArchivo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmCrearArchivo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmCrearArchivo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmCrearArchivo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmCrearArchivo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private MaterialSwing.MaterialButtomPanel btnCrearLg1;
    private MaterialSwing.MaterialButtomPanel btnGuardar;
    private MaterialSwing.MaterialButtomPanel btnGuardarComo;
    private MaterialSwing.MaterialButtomPanel btnInicioXs;
    private MaterialSwing.MaterialButtomPanel btnMadalineLg1;
    private MaterialSwing.MaterialButtomPanel btnPerceptronLg1;
    private MaterialSwing.MaterialButtomPanel btnSalirLg1;
    private MaterialSwing.MaterialButtomPanel btnSimularLg1;
    private MaterialSwing.MaterialButtomPanel btnVerRegistrosLg1;
    private javax.swing.JFileChooser fileChooser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblNumeroEntradas;
    private javax.swing.JLabel lblNumeroEntradas1;
    private javax.swing.JLabel lblNumeroPatrones;
    private javax.swing.JLabel lblNumeroPatrones1;
    private MaterialSwing.MaterialButtomPanel materialButtomPanel2;
    private javax.swing.JPanel paneTitulo;
    private javax.swing.JPanel panelCardLayout;
    private javax.swing.JPanel panelCuerpo;
    private javax.swing.JPanel panelIconoMenu;
    private MaterialSwing.MaterialButtomPanel panelMenu;
    private javax.swing.JPanel panelMenuMinimizado;
    private javax.swing.JTable tabla;
    private MaterialSwing.MaterialTextField txtColumnas;
    private MaterialSwing.MaterialTextField txtFilas;
    // End of variables declaration//GEN-END:variables

    public void setColor(JPanel panel) {
        /*panel.setBackground(new java.awt.Color(255, 255, 255));
        panel.setBorder(BorderFactory.createLineBorder(Color.WHITE));*/
    }

    public void resetColor(JPanel panel) {
        /* panel.setBackground(new java.awt.Color(204, 204, 204));*/
    }

    public void setEnableContainer(Container c, boolean band) {

        Component[] components = c.getComponents();
        c.setEnabled(band);
        for (int i = 0; i < components.length; i++) {
            components[i].setEnabled(band);

            if (components[i] instanceof Container) {
                setEnableContainer((Container) components[i], band);
            }

        }

    }

    private double[][] abrirArchivo(String cadena) {
        tabla.removeAll();
        JFileChooser fileChooser = new JFileChooser();

        fileChooser.setDialogTitle("Cargar " + cadena);
        fileChooser.setFileFilter(new miFiltro());
        int returnVal = fileChooser.showOpenDialog(null);
        String linea;
        double[][] mat;
        ArrayList lista = new ArrayList();
        if (returnVal == JFileChooser.APPROVE_OPTION) {

            File file = fileChooser.getSelectedFile();
            ruta = fileChooser.getSelectedFile().toString();
            System.out.println("ruta " + ruta);
            try {
                if (file == null) {
                    JOptionPane.showMessageDialog(null, "\nNo se ha encontrado el archivo o \n esta inaccesible en estos momentos", "ADVERTENCIA!!!", JOptionPane.WARNING_MESSAGE);
                } else {
                    FileReader archivos = new FileReader(file);
                    BufferedReader lee = new BufferedReader(archivos);
                    int cont = 0;
                    while ((linea = lee.readLine()) != null) {
                        lista.add(linea.split(" "));
                    }
                    lee.close();
                    //actualizar la Tabla con el archivo que acabamode leer

                    Object[] get = (Object[]) lista.get(0);
                    mat = new double[lista.size()][get.length];

                    for (int i = 0; i < lista.size(); i++) {
                        get = (Object[]) lista.get(i);
                        for (int j = 0; j < get.length; j++) {
                            mat[i][j] = Double.parseDouble((String) get[j]);

                        }
                        System.out.println("");
                    }
                    filas = lista.size();
                    columnas = get.length;
                    System.out.println("" + columnas);
                    txtColumnas.setText("" + columnas);
                    txtFilas.setText("" + filas);
                    modelarTabla();

                    for (int i = 0; i < mat.length; i++) {
                        for (int k = 0; k < get.length; k++) {
                            System.out.print("x[" + k + "]: " + mat[i][k] + " ");
                            tabla.setValueAt(mat[i][k], i, k);
                        }
                        System.out.println("");
                    }

                    System.out.println("Patrones: " + filas);
                    btnGuardar.setVisible(true);
                    matE = mat;
                    return mat;
                }
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(null, ex + "" + "\nNo se ha encontrado el archivo", "ADVERTENCIA!!!", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(null, "\nOpeeracion cancelada por el usuario", "ADVERTENCIA!!!", JOptionPane.WARNING_MESSAGE);

        }
        return null;
    }

    private void subirNumero(JTextField txtText) {
        double num;
        if (txtText.getText().equals("")) {
            txtText.setText("0.0");
        }
        num = Double.parseDouble(txtText.getText());
        txtText.setText(String.valueOf(num + 1));
    }

    private void bajarNumero(JTextField txtText) {
        double num;
        if (txtText.getText().equals("")) {
            txtText.setText("0.0");
        }
        num = Double.parseDouble(txtText.getText());
        if (num > 0) {
            txtText.setText(String.valueOf(num - 1));
        } else {
            getToolkit().beep();
        }
    }

    private void guardarArchivo() {
        try {
            if (true) {
                //Aqui ya tiens la ruta,,,ahora puedes crear un fichero n esa ruta y escribir lo k kieras...
                File archivo = new File(ruta);
                boolean seguir = true;
                if (seguir) {
                    try {
                        String cad;
                        try (FileWriter fw = new FileWriter(archivo, false)) {
                            PrintWriter pw = new PrintWriter(fw);
                            for (int i = 0; i < tabla.getRowCount(); i++) {
                                cad = "";
                                for (int j = 0; j < tabla.getColumnCount(); j++) {
                                    cad = cad + (tabla.getValueAt(i, j) + " ");
                                }
                                pw.println(cad);
                            }

                        }

                    } catch (IOException ex) {
                        System.err.print("Excepcion: " + ex.getMessage());
                    }
                    JOptionPane.showMessageDialog(null, "Archivo Guardado exitoso!", "Guardando", JOptionPane.INFORMATION_MESSAGE);
                }

            }
        } catch (HeadlessException ex) {
            JOptionPane.showMessageDialog(null, "Error al guardar el archivo!", "Oops! Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    String ruta;

    private void guardarArchivoComo() {

        try {
            if (fileChooser.showSaveDialog(null) == JFileChooser.APPROVE_OPTION) {
                ruta = fileChooser.getSelectedFile().getAbsolutePath();
                //Aqui ya tiens la ruta,,,ahora puedes crear un fichero n esa ruta y escribir lo k kieras...
                File archivo = new File(ruta);
                boolean seguir = true;
                if (archivo.exists()) {
                    if (JOptionPane.OK_OPTION != JOptionPane.showConfirmDialog(this, "El fichero existe,deseas reemplazarlo?", "Titulo", JOptionPane.YES_NO_OPTION)) {
                        seguir = false;
                    }
                }

                if (seguir) {
                    try {
                        String cad;
                        try (FileWriter fw = new FileWriter(archivo, true)) {
                            PrintWriter pw = new PrintWriter(fw);
                            for (int i = 0; i < tabla.getRowCount(); i++) {
                                cad = "";
                                for (int j = 0; j < tabla.getColumnCount(); j++) {
                                    cad = cad + (tabla.getValueAt(i, j) + " ");
                                }
                                pw.println(cad);
                            }
                        }

                    } catch (IOException ex) {
                        System.err.print("Excepcion: " + ex.getMessage());
                    }
                    if (!(ruta.endsWith(".txt"))) {
                        File temp = new File(ruta + ".txt");
                        fileChooser.getSelectedFile().renameTo(temp);//renombramos el archivo
                    }

                    JOptionPane.showMessageDialog(null, "Archivo Guardado exitoso!", "Guardando", JOptionPane.INFORMATION_MESSAGE);
                }

            }
        } catch (HeadlessException ex) {
            JOptionPane.showMessageDialog(null, "Error al guardar el archivo!", "Oops! Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void modelarTabla() {
        tabla.setVisible(true);
        fil = (Integer.parseInt(txtFilas.getText()));
        col = (Integer.parseInt(txtColumnas.getText()));

        String cad[] = new String[col];
        for (int i = 0; i < col; i++) {
            cad[i] = "x" + (i + 1);
        }

        Class[] tipo = new Class[col];
        for (int i = 0; i < col; i++) {
            tipo[i] = java.lang.Double.class;
        }

        Object ob[][] = new Object[fil][col];
        for (int i = 0; i < fil; i++) {
            for (int j = 0; j < col; j++) {
                ob[i][j] = 0;
            }
        }

        tabla.setModel(new javax.swing.table.DefaultTableModel(
                ob,
                cad) {
            Class[] types = tipo;

            public Class getColumnClass(int columnIndex) {
                return types[columnIndex];
            }
        });
        //tabla.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        tabla.setColumnSelectionAllowed(true);
        tabla.getTableHeader().setReorderingAllowed(false);
//        jScrollPane1.setViewportView(tabla);
//        jScrollPane1.setBounds(20, 80, col*83, fil*24);
        tabla.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
    }

}
