/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.RendererArbol;
import java.awt.Component;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTree;
import javax.swing.UIManager;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeCellRenderer;
import javax.swing.tree.DefaultTreeModel;
import javax.swing.tree.TreeNode;
import javax.swing.tree.TreePath;

/**
 *
 * @author proxc
 */
public class FrmConsultarArchivos extends javax.swing.JFrame {

    /**
     * Creates new form Home_Data
     */
    private int m;
    private int n;
    private int p;
    private double[][] x;
    private double[][] yd;
    
    public FrmConsultarArchivos() {
        initComponents();
        Animacion.Animacion.mover_izquierda(0, -264, 2, 2, panelMenuMinimizado);
        crearArbol();
        listarArchivos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        panelCuerpo = new javax.swing.JPanel();
        paneTitulo = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        panelCardLayout = new javax.swing.JPanel();
        scrol = new javax.swing.JScrollPane();
        arbol = new javax.swing.JTree();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel16 = new javax.swing.JLabel();
        cbxNombreRed = new javax.swing.JComboBox<>();
        cbxNombreArchivo = new javax.swing.JComboBox<>();
        panelIconoMenu = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        panelMenu = new MaterialSwing.MaterialButtomPanel();
        jLabel23 = new javax.swing.JLabel();
        panelMenuMinimizado = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        btnInicioXs = new MaterialSwing.MaterialButtomPanel();
        jLabel27 = new javax.swing.JLabel();
        btnMadalineLg1 = new MaterialSwing.MaterialButtomPanel();
        jLabel28 = new javax.swing.JLabel();
        btnPerceptronLg1 = new MaterialSwing.MaterialButtomPanel();
        jLabel43 = new javax.swing.JLabel();
        btnSimularLg1 = new MaterialSwing.MaterialButtomPanel();
        jLabel33 = new javax.swing.JLabel();
        btnCrearLg1 = new MaterialSwing.MaterialButtomPanel();
        jLabel35 = new javax.swing.JLabel();
        btnVerRegistrosLg1 = new MaterialSwing.MaterialButtomPanel();
        jLabel44 = new javax.swing.JLabel();
        btnSalirLg1 = new MaterialSwing.MaterialButtomPanel();
        jLabel45 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                formMouseMoved(evt);
            }
        });

        panelCuerpo.setBackground(new java.awt.Color(255, 255, 255));
        panelCuerpo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        paneTitulo.setBackground(new java.awt.Color(255, 255, 255));
        org.jdesktop.swingx.border.DropShadowBorder dropShadowBorder1 = new org.jdesktop.swingx.border.DropShadowBorder();
        dropShadowBorder1.setShadowSize(10);
        dropShadowBorder1.setShowRightShadow(false);
        paneTitulo.setBorder(dropShadowBorder1);

        jPanel5.setBackground(new java.awt.Color(139, 195, 74));

        jLabel15.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/images/icons8_Search_Property_48px_1.png"))); // NOI18N
        jLabel15.setText("Consultar Archivos");

        jPanel1.setBackground(new java.awt.Color(104, 159, 56));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 18, Short.MAX_VALUE)
        );

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/images/logo U.png"))); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 569, Short.MAX_VALUE)
                .addComponent(jLabel21)
                .addGap(28, 28, 28))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel21)
                    .addComponent(jLabel15))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout paneTituloLayout = new javax.swing.GroupLayout(paneTitulo);
        paneTitulo.setLayout(paneTituloLayout);
        paneTituloLayout.setHorizontalGroup(
            paneTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneTituloLayout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        paneTituloLayout.setVerticalGroup(
            paneTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        panelCuerpo.add(paneTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 140));

        panelCardLayout.setBackground(new java.awt.Color(255, 255, 255));
        org.jdesktop.swingx.border.DropShadowBorder dropShadowBorder2 = new org.jdesktop.swingx.border.DropShadowBorder();
        dropShadowBorder2.setShowLeftShadow(true);
        dropShadowBorder2.setShowTopShadow(true);
        panelCardLayout.setBorder(dropShadowBorder2);

        org.jdesktop.swingx.border.DropShadowBorder dropShadowBorder3 = new org.jdesktop.swingx.border.DropShadowBorder();
        dropShadowBorder3.setShowLeftShadow(true);
        dropShadowBorder3.setShowTopShadow(true);
        scrol.setBorder(dropShadowBorder3);

        arbol.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                arbolMouseEntered(evt);
            }
        });
        arbol.addTreeSelectionListener(new javax.swing.event.TreeSelectionListener() {
            public void valueChanged(javax.swing.event.TreeSelectionEvent evt) {
                arbolValueChanged(evt);
            }
        });
        scrol.setViewportView(arbol);

        jScrollPane1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel16.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("listado de redes");

        cbxNombreRed.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "nombre" }));
        cbxNombreRed.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxNombreRedItemStateChanged(evt);
            }
        });

        cbxNombreArchivo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "archivo" }));
        cbxNombreArchivo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxNombreArchivoItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout panelCardLayoutLayout = new javax.swing.GroupLayout(panelCardLayout);
        panelCardLayout.setLayout(panelCardLayoutLayout);
        panelCardLayoutLayout.setHorizontalGroup(
            panelCardLayoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCardLayoutLayout.createSequentialGroup()
                .addGroup(panelCardLayoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCardLayoutLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(scrol, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelCardLayoutLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel16)))
                .addGap(23, 23, 23)
                .addGroup(panelCardLayoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCardLayoutLayout.createSequentialGroup()
                        .addComponent(cbxNombreRed, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cbxNombreArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        panelCardLayoutLayout.setVerticalGroup(
            panelCardLayoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCardLayoutLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(panelCardLayoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(cbxNombreRed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxNombreArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelCardLayoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(scrol, javax.swing.GroupLayout.DEFAULT_SIZE, 366, Short.MAX_VALUE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        panelCuerpo.add(panelCardLayout, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 145, 740, 450));

        panelIconoMenu.setBackground(new java.awt.Color(255, 255, 255));
        org.jdesktop.swingx.border.DropShadowBorder dropShadowBorder4 = new org.jdesktop.swingx.border.DropShadowBorder();
        dropShadowBorder4.setShadowSize(10);
        panelIconoMenu.setBorder(dropShadowBorder4);

        jPanel6.setBackground(new java.awt.Color(94, 94, 95));
        jPanel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel6MouseClicked(evt);
            }
        });

        panelMenu.setBackground(new java.awt.Color(94, 94, 95));
        panelMenu.setPreferredSize(new java.awt.Dimension(53, 40));
        panelMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelMenuMouseClicked(evt);
            }
        });

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/images/icons8_Menu_24px.png"))); // NOI18N
        jLabel23.setMaximumSize(new java.awt.Dimension(32, 32));
        jLabel23.setMinimumSize(new java.awt.Dimension(32, 32));
        jLabel23.setName(""); // NOI18N
        jLabel23.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout panelMenuLayout = new javax.swing.GroupLayout(panelMenu);
        panelMenu.setLayout(panelMenuLayout);
        panelMenuLayout.setHorizontalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelMenuLayout.setVerticalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuLayout.createSequentialGroup()
                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 10, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 53, Short.MAX_VALUE)
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addComponent(panelMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 34, Short.MAX_VALUE)
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addComponent(panelMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 12, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout panelIconoMenuLayout = new javax.swing.GroupLayout(panelIconoMenu);
        panelIconoMenu.setLayout(panelIconoMenuLayout);
        panelIconoMenuLayout.setHorizontalGroup(
            panelIconoMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelIconoMenuLayout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelIconoMenuLayout.setVerticalGroup(
            panelIconoMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelIconoMenuLayout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelCuerpo.add(panelIconoMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 60, 40));

        panelMenuMinimizado.setBackground(new java.awt.Color(255, 255, 255));
        org.jdesktop.swingx.border.DropShadowBorder dropShadowBorder5 = new org.jdesktop.swingx.border.DropShadowBorder();
        dropShadowBorder5.setShadowSize(10);
        panelMenuMinimizado.setBorder(dropShadowBorder5);

        jPanel3.setBackground(new java.awt.Color(94, 94, 95));

        btnInicioXs.setBackground(new java.awt.Color(94, 94, 95));
        btnInicioXs.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        btnInicioXs.setPreferredSize(new java.awt.Dimension(53, 40));
        btnInicioXs.setRippleColor(new java.awt.Color(51, 204, 0));
        btnInicioXs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnInicioXsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnInicioXsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnInicioXsMouseExited(evt);
            }
        });

        jLabel27.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 12)); // NOI18N
        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/images/icons8_Home_24px_2.png"))); // NOI18N
        jLabel27.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jLabel27.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel27MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout btnInicioXsLayout = new javax.swing.GroupLayout(btnInicioXs);
        btnInicioXs.setLayout(btnInicioXsLayout);
        btnInicioXsLayout.setHorizontalGroup(
            btnInicioXsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnInicioXsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btnInicioXsLayout.setVerticalGroup(
            btnInicioXsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnInicioXsLayout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(jLabel27)
                .addContainerGap())
        );

        btnMadalineLg1.setBackground(new java.awt.Color(94, 94, 95));
        btnMadalineLg1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        btnMadalineLg1.setPreferredSize(new java.awt.Dimension(53, 40));
        btnMadalineLg1.setRippleColor(new java.awt.Color(51, 204, 0));
        btnMadalineLg1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMadalineLg1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMadalineLg1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMadalineLg1MouseExited(evt);
            }
        });

        jLabel28.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/images/icons8_Brain_24px.png"))); // NOI18N
        jLabel28.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout btnMadalineLg1Layout = new javax.swing.GroupLayout(btnMadalineLg1);
        btnMadalineLg1.setLayout(btnMadalineLg1Layout);
        btnMadalineLg1Layout.setHorizontalGroup(
            btnMadalineLg1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnMadalineLg1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel28, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE))
        );
        btnMadalineLg1Layout.setVerticalGroup(
            btnMadalineLg1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnMadalineLg1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jLabel28)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        btnPerceptronLg1.setBackground(new java.awt.Color(94, 94, 95));
        btnPerceptronLg1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        btnPerceptronLg1.setPreferredSize(new java.awt.Dimension(53, 40));
        btnPerceptronLg1.setRippleColor(new java.awt.Color(51, 204, 0));
        btnPerceptronLg1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPerceptronLg1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnPerceptronLg1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnPerceptronLg1MouseExited(evt);
            }
        });

        jLabel43.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 12)); // NOI18N
        jLabel43.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/images/icons8_Google_Scholar_24px_2.png"))); // NOI18N
        jLabel43.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout btnPerceptronLg1Layout = new javax.swing.GroupLayout(btnPerceptronLg1);
        btnPerceptronLg1.setLayout(btnPerceptronLg1Layout);
        btnPerceptronLg1Layout.setHorizontalGroup(
            btnPerceptronLg1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnPerceptronLg1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel43, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btnPerceptronLg1Layout.setVerticalGroup(
            btnPerceptronLg1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnPerceptronLg1Layout.createSequentialGroup()
                .addComponent(jLabel43)
                .addGap(0, 12, Short.MAX_VALUE))
        );

        btnSimularLg1.setBackground(new java.awt.Color(94, 94, 95));
        btnSimularLg1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        btnSimularLg1.setPreferredSize(new java.awt.Dimension(53, 40));
        btnSimularLg1.setRippleColor(new java.awt.Color(51, 204, 0));
        btnSimularLg1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSimularLg1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSimularLg1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSimularLg1MouseExited(evt);
            }
        });

        jLabel33.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 12)); // NOI18N
        jLabel33.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/images/icons8_HIPS_24px_2.png"))); // NOI18N
        jLabel33.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout btnSimularLg1Layout = new javax.swing.GroupLayout(btnSimularLg1);
        btnSimularLg1.setLayout(btnSimularLg1Layout);
        btnSimularLg1Layout.setHorizontalGroup(
            btnSimularLg1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnSimularLg1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel33)
                .addGap(60, 60, 60))
        );
        btnSimularLg1Layout.setVerticalGroup(
            btnSimularLg1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnSimularLg1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jLabel33)
                .addGap(20, 20, 20))
        );

        btnCrearLg1.setBackground(new java.awt.Color(94, 94, 95));
        btnCrearLg1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        btnCrearLg1.setPreferredSize(new java.awt.Dimension(53, 40));
        btnCrearLg1.setRippleColor(new java.awt.Color(51, 204, 0));
        btnCrearLg1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCrearLg1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCrearLg1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCrearLg1MouseExited(evt);
            }
        });

        jLabel35.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 12)); // NOI18N
        jLabel35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/images/icons8_Edit_Property_24px.png"))); // NOI18N
        jLabel35.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout btnCrearLg1Layout = new javax.swing.GroupLayout(btnCrearLg1);
        btnCrearLg1.setLayout(btnCrearLg1Layout);
        btnCrearLg1Layout.setHorizontalGroup(
            btnCrearLg1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnCrearLg1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel35)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        btnCrearLg1Layout.setVerticalGroup(
            btnCrearLg1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnCrearLg1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jLabel35)
                .addContainerGap())
        );

        btnVerRegistrosLg1.setBackground(new java.awt.Color(94, 94, 95));
        btnVerRegistrosLg1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        btnVerRegistrosLg1.setPreferredSize(new java.awt.Dimension(53, 40));
        btnVerRegistrosLg1.setRippleColor(new java.awt.Color(51, 204, 0));
        btnVerRegistrosLg1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVerRegistrosLg1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnVerRegistrosLg1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnVerRegistrosLg1MouseExited(evt);
            }
        });

        jLabel44.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 12)); // NOI18N
        jLabel44.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/images/icons8_Search_Property_24px_1.png"))); // NOI18N
        jLabel44.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout btnVerRegistrosLg1Layout = new javax.swing.GroupLayout(btnVerRegistrosLg1);
        btnVerRegistrosLg1.setLayout(btnVerRegistrosLg1Layout);
        btnVerRegistrosLg1Layout.setHorizontalGroup(
            btnVerRegistrosLg1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnVerRegistrosLg1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel44, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE))
        );
        btnVerRegistrosLg1Layout.setVerticalGroup(
            btnVerRegistrosLg1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnVerRegistrosLg1Layout.createSequentialGroup()
                .addComponent(jLabel44)
                .addGap(0, 12, Short.MAX_VALUE))
        );

        btnSalirLg1.setBackground(new java.awt.Color(94, 94, 95));
        btnSalirLg1.setPreferredSize(new java.awt.Dimension(53, 43));
        btnSalirLg1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSalirLg1MouseClicked(evt);
            }
        });

        jLabel45.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/images/icons8_Exit_Sign_24px_3.png"))); // NOI18N

        javax.swing.GroupLayout btnSalirLg1Layout = new javax.swing.GroupLayout(btnSalirLg1);
        btnSalirLg1.setLayout(btnSalirLg1Layout);
        btnSalirLg1Layout.setHorizontalGroup(
            btnSalirLg1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnSalirLg1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel45, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(19, 19, 19))
        );
        btnSalirLg1Layout.setVerticalGroup(
            btnSalirLg1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnSalirLg1Layout.createSequentialGroup()
                .addComponent(jLabel45, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnPerceptronLg1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btnSimularLg1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btnCrearLg1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btnMadalineLg1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btnInicioXs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btnVerRegistrosLg1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btnSalirLg1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(btnInicioXs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnMadalineLg1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnPerceptronLg1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnSimularLg1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnCrearLg1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnVerRegistrosLg1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSalirLg1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout panelMenuMinimizadoLayout = new javax.swing.GroupLayout(panelMenuMinimizado);
        panelMenuMinimizado.setLayout(panelMenuMinimizadoLayout);
        panelMenuMinimizadoLayout.setHorizontalGroup(
            panelMenuMinimizadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuMinimizadoLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelMenuMinimizadoLayout.setVerticalGroup(
            panelMenuMinimizadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        panelCuerpo.add(panelMenuMinimizado, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 60, 360));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelCuerpo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelCuerpo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInicioXsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInicioXsMouseClicked
        // TODO add your handling code here:
        new FrmInicio().setVisible(true);
    }//GEN-LAST:event_btnInicioXsMouseClicked

    private void btnInicioXsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInicioXsMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnInicioXsMouseEntered

    private void btnInicioXsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInicioXsMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnInicioXsMouseExited

    private void btnMadalineLg1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMadalineLg1MouseClicked
        // TODO add your handling code here:
        new FrmCrearArchivo().setVisible(true);
    }//GEN-LAST:event_btnMadalineLg1MouseClicked

    private void btnMadalineLg1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMadalineLg1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMadalineLg1MouseEntered

    private void btnMadalineLg1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMadalineLg1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMadalineLg1MouseExited

    private void btnPerceptronLg1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPerceptronLg1MouseClicked
        // TODO add your handling code here:
        new FrmPerceptron().setVisible(true);
    }//GEN-LAST:event_btnPerceptronLg1MouseClicked

    private void btnPerceptronLg1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPerceptronLg1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPerceptronLg1MouseEntered

    private void btnPerceptronLg1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPerceptronLg1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPerceptronLg1MouseExited

    private void btnSimularLg1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSimularLg1MouseClicked
        // TODO add your handling code here:
        new FrmSimular().setVisible(true);
    }//GEN-LAST:event_btnSimularLg1MouseClicked

    private void btnSimularLg1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSimularLg1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSimularLg1MouseEntered

    private void btnSimularLg1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSimularLg1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSimularLg1MouseExited

    private void btnCrearLg1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCrearLg1MouseClicked
        // TODO add your handling code here:
        new FrmCrearArchivo().setVisible(true);
    }//GEN-LAST:event_btnCrearLg1MouseClicked

    private void btnCrearLg1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCrearLg1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCrearLg1MouseEntered

    private void btnCrearLg1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCrearLg1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCrearLg1MouseExited

    private void btnVerRegistrosLg1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVerRegistrosLg1MouseClicked
        // TODO add your handling code here:
        new FrmConsultarArchivos().setVisible(true);
    }//GEN-LAST:event_btnVerRegistrosLg1MouseClicked

    private void btnVerRegistrosLg1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVerRegistrosLg1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVerRegistrosLg1MouseEntered

    private void btnVerRegistrosLg1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVerRegistrosLg1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVerRegistrosLg1MouseExited

    private void btnSalirLg1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirLg1MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnSalirLg1MouseClicked

    private void formMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseMoved
        // TODO add your handling code here:
        if (rootPaneCheckingEnabled) {
            
        }
    }//GEN-LAST:event_formMouseMoved

    private void panelMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelMenuMouseClicked
        // TODO add your handling code here:
        int posicion = panelMenuMinimizado.getX();
        if (posicion > -1) {
            Animacion.Animacion.mover_izquierda(0, -264, 2, 2, panelMenuMinimizado);
        } else {
            Animacion.Animacion.mover_derecha(-264, 0, 2, 2, panelMenuMinimizado);
        }
    }//GEN-LAST:event_panelMenuMouseClicked

    private void cbxNombreArchivoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxNombreArchivoItemStateChanged
        // TODO add your handling code here:;
        if (es) {

            String cadena = System.getProperty("user.dir") + "\\RedesNeuronales\\" + cbxNombreRed.getSelectedItem() + "\\" + cbxNombreArchivo.getSelectedItem();
            jTextArea1.setText("");
            File file = new File(cadena);
            try {
                if (file == null) {
                    JOptionPane.showMessageDialog(null, "\nNo se ha encontrado el archivo o \n esta inaccesible en estos momentos", "ADVERTENCIA!!!", JOptionPane.WARNING_MESSAGE);
                } else {
                    FileReader archivos = new FileReader(file);
                    BufferedReader lee = new BufferedReader(archivos);
                    String linea;
                    while ((linea = lee.readLine()) != null) {
                        jTextArea1.append(linea + "\n");
                    }
                    lee.close();
                }
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(null, ex + "" + "\nNo se ha encontrado el archivo", "ADVERTENCIA!!!", JOptionPane.ERROR_MESSAGE);
            }

            System.out.println(cadena);
            System.out.println("");

        }
    }//GEN-LAST:event_cbxNombreArchivoItemStateChanged

    private void cbxNombreRedItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxNombreRedItemStateChanged
        // TODO add your handling code here:
        es = false;
        String sDirectorio = System.getProperty("user.dir") + "\\RedesNeuronales\\" + cbxNombreRed.getSelectedItem();
        cbxNombreArchivo.removeAllItems();
        cbxNombreArchivo.addItem("Archivo");
        File f = new File(sDirectorio);
        if (f.exists()) { // Directorio existe
            File[] ficheros = f.listFiles();
            for (int x = 0; x < ficheros.length; x++) {
                cbxNombreArchivo.addItem(ficheros[x].getName());
            }
        }
        es = true;
    }//GEN-LAST:event_cbxNombreRedItemStateChanged

    private void arbolValueChanged(javax.swing.event.TreeSelectionEvent evt) {//GEN-FIRST:event_arbolValueChanged
        // TODO add your handling code here:
        // Obtenemos y escribimos en pantalla  el path seleccionado
        jTextArea1.removeAll();
        jTextArea1.setText("");
        TreePath path = evt.getPath();
        Object[] nodos = path.getPath();
        System.out.print("Path seleccionado: ");
        String cadena = System.getProperty("user.dir") + "\\";
        for (Object nodo : nodos) {
            System.out.print(nodo.toString() + " | ");
            cadena = cadena + nodo.toString() + "\\";
        }
        cadena.substring(0, cadena.length() - 3);
        if (cadena.contains(".")) {

            File file = new File(cadena);
            try {
                if (file == null) {
                    JOptionPane.showMessageDialog(null, "\nNo se ha encontrado el archivo o \n esta inaccesible en estos momentos", "ADVERTENCIA!!!", JOptionPane.WARNING_MESSAGE);
                } else {
                    FileReader archivos = new FileReader(file);
                    BufferedReader lee = new BufferedReader(archivos);
                    String linea;
                    while ((linea = lee.readLine()) != null) {
                        jTextArea1.append(linea + "\n");
                    }
                    lee.close();
                }
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(null, ex + "" + "\nNo se ha encontrado el archivo", "ADVERTENCIA!!!", JOptionPane.ERROR_MESSAGE);
            }

        }
        System.out.println(cadena);
        System.out.println("");

    }//GEN-LAST:event_arbolValueChanged

    private void arbolMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_arbolMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_arbolMouseEntered

    private void jPanel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MouseClicked
        // TODO add your handling code here:
        int pos = this.panelIconoMenu.getX();
        if (pos < 0) {
            Animacion.Animacion.mover_derecha(0, -256, 3, 3, panelMenuMinimizado);
        } else {
            Animacion.Animacion.mover_izquierda(-256, 0, 3, 3, panelMenuMinimizado);
        }
    }//GEN-LAST:event_jPanel6MouseClicked

    private void jLabel27MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel27MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel27MouseClicked
    boolean es = false;
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmConsultarArchivos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmConsultarArchivos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmConsultarArchivos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmConsultarArchivos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmConsultarArchivos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTree arbol;
    private MaterialSwing.MaterialButtomPanel btnCrearLg1;
    private MaterialSwing.MaterialButtomPanel btnInicioXs;
    private MaterialSwing.MaterialButtomPanel btnMadalineLg1;
    private MaterialSwing.MaterialButtomPanel btnPerceptronLg1;
    private MaterialSwing.MaterialButtomPanel btnSalirLg1;
    private MaterialSwing.MaterialButtomPanel btnSimularLg1;
    private MaterialSwing.MaterialButtomPanel btnVerRegistrosLg1;
    private javax.swing.JComboBox<String> cbxNombreArchivo;
    private javax.swing.JComboBox<String> cbxNombreRed;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JPanel paneTitulo;
    private javax.swing.JPanel panelCardLayout;
    private javax.swing.JPanel panelCuerpo;
    private javax.swing.JPanel panelIconoMenu;
    private MaterialSwing.MaterialButtomPanel panelMenu;
    private javax.swing.JPanel panelMenuMinimizado;
    private javax.swing.JScrollPane scrol;
    // End of variables declaration//GEN-END:variables

    public void setColor(JPanel panel) {
        /*panel.setBackground(new java.awt.Color(255, 255, 255));
        panel.setBorder(BorderFactory.createLineBorder(Color.WHITE));*/
    }
    
    public void resetColor(JPanel panel) {
        /* panel.setBackground(new java.awt.Color(204, 204, 204));*/
    }
    
    public void crearArbol() {
        // TODO add your handling code here:
        //create the root node
        DefaultMutableTreeNode root = new DefaultMutableTreeNode("RedesNeuronales");
        //create the child nodes
        String sDirectorio = System.getProperty("user.dir") + "\\RedesNeuronales";
        File f = new File(sDirectorio);
        if (f.exists()) { // Directorio existe 
            File[] ficheros = f.listFiles();
            for (File fichero : ficheros) {
                // System.out.println(fichero.getName());
                DefaultMutableTreeNode nodo = new DefaultMutableTreeNode(fichero.getName());
                File fh = new File(sDirectorio + "\\" + fichero.getName());
                File[] ficherosH = fh.listFiles();
                for (File ficheroH : ficherosH) {
                    //System.out.println(ficheroH.getName());
                    nodo.add(new DefaultMutableTreeNode(ficheroH.getName()));
                }
                root.add(nodo);
            }
        } else {
            f.mkdir();
        }

        //create the tree by passing in the root node
        DefaultTreeModel modelo;
        modelo = new DefaultTreeModel(root);
        arbol.setModel(modelo);
        arbol.setCellRenderer(new RendererArbol());
        arbol.setEditable(true);
        
    }
    
    public void listarArchivos() {
        String sDirectorio = System.getProperty("user.dir") + "\\RedesNeuronales";
        File f = new File(sDirectorio);
        if (f.exists()) { // Directorio existe 
            File[] ficheros = f.listFiles();
            for (File fichero : ficheros) {
                cbxNombreRed.addItem(fichero.getName());
            }
        }
    }
    
   
}
