/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.progresBar;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Component;
import java.awt.Container;
import java.awt.FlowLayout;
import java.awt.GradientPaint;
import java.awt.GridLayout;
import java.io.File;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.UIManager;
import modelo.getSetPesosUmbrales;
import modelo.madalineDCO;
import modelo.madalineTCO;
import modelo.madalineUCO;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.axis.CategoryAxis;
import org.jfree.chart.axis.CategoryLabelPositions;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.chart.renderer.category.BarRenderer;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author proxc
 */
public class FrmSimular extends javax.swing.JFrame {

    /**
     * Creates new form Home_Data
     */
    madalineDCO md2;
    madalineUCO md1;
    madalineTCO md3;
    Thread hilo;
    Thread hiloProgresBar;
    progresBar pg;
    public static boolean band = true;
    getSetPesosUmbrales gspu;

    public FrmSimular() {
        initComponents();
        Animacion.Animacion.mover_izquierda(0, -264, 2, 2, panelMenuMinimizado);
        listarArchivos();
        panelTipoSimulacion.setVisible(false);
        panelContenido.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        panelCuerpo = new javax.swing.JPanel();
        paneTitulo = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        panelIconoMenu = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        panelMenu = new MaterialSwing.MaterialButtomPanel();
        jLabel23 = new javax.swing.JLabel();
        panelMenuMinimizado = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        btnInicioXs = new MaterialSwing.MaterialButtomPanel();
        jLabel27 = new javax.swing.JLabel();
        btnMadalineLg1 = new MaterialSwing.MaterialButtomPanel();
        jLabel28 = new javax.swing.JLabel();
        btnPerceptronLg1 = new MaterialSwing.MaterialButtomPanel();
        jLabel43 = new javax.swing.JLabel();
        btnSimularLg1 = new MaterialSwing.MaterialButtomPanel();
        jLabel33 = new javax.swing.JLabel();
        btnCrearLg1 = new MaterialSwing.MaterialButtomPanel();
        jLabel35 = new javax.swing.JLabel();
        btnVerRegistrosLg1 = new MaterialSwing.MaterialButtomPanel();
        jLabel44 = new javax.swing.JLabel();
        btnSalirLg1 = new MaterialSwing.MaterialButtomPanel();
        jLabel45 = new javax.swing.JLabel();
        panelCardLayout = new javax.swing.JPanel();
        panelContenido = new javax.swing.JPanel();
        panelSimulacionPersonalizada = new javax.swing.JPanel();
        panelEntradasSimulacion = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        textAreaEntradas = new javax.swing.JTextArea();
        btnSimulacionPersonalizada1 = new MaterialSwing.MaterialButtomPanel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        textAreaSalidas = new javax.swing.JTextArea();
        jSeparator1 = new javax.swing.JSeparator();
        GraficaPersonalizada = new javax.swing.JPanel();
        panelSimulacionGeneral = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        panelGraficaGeneralzada = new javax.swing.JPanel();
        cbxNombreRed = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        rdoSupervisadas = new javax.swing.JRadioButton();
        rdoBasesRadiales = new javax.swing.JRadioButton();
        rdoNosupervisadas = new javax.swing.JRadioButton();
        panelTipoSimulacion = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        switchTipoSimulacion = new MaterialSwing.MaterialSwitch();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                formMouseMoved(evt);
            }
        });

        panelCuerpo.setBackground(new java.awt.Color(255, 255, 255));
        panelCuerpo.setMinimumSize(new java.awt.Dimension(890, 700));

        paneTitulo.setBackground(new java.awt.Color(255, 255, 255));
        org.jdesktop.swingx.border.DropShadowBorder dropShadowBorder1 = new org.jdesktop.swingx.border.DropShadowBorder();
        dropShadowBorder1.setShadowSize(10);
        dropShadowBorder1.setShowRightShadow(false);
        paneTitulo.setBorder(dropShadowBorder1);

        jPanel5.setBackground(new java.awt.Color(139, 195, 74));

        jLabel15.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/images/icons8_System_Task_48px_1.png"))); // NOI18N
        jLabel15.setText("Simulacion");

        jPanel1.setBackground(new java.awt.Color(104, 159, 56));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 18, Short.MAX_VALUE)
        );

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/images/logo U.png"))); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel21)
                .addGap(28, 28, 28))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel21)
                    .addComponent(jLabel15))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout paneTituloLayout = new javax.swing.GroupLayout(paneTitulo);
        paneTitulo.setLayout(paneTituloLayout);
        paneTituloLayout.setHorizontalGroup(
            paneTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneTituloLayout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        paneTituloLayout.setVerticalGroup(
            paneTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        panelIconoMenu.setBackground(new java.awt.Color(255, 255, 255));
        org.jdesktop.swingx.border.DropShadowBorder dropShadowBorder2 = new org.jdesktop.swingx.border.DropShadowBorder();
        dropShadowBorder2.setShadowSize(10);
        panelIconoMenu.setBorder(dropShadowBorder2);

        jPanel6.setBackground(new java.awt.Color(94, 94, 95));

        panelMenu.setBackground(new java.awt.Color(94, 94, 95));
        panelMenu.setPreferredSize(new java.awt.Dimension(53, 40));
        panelMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelMenuMouseClicked(evt);
            }
        });

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/images/icons8_Menu_24px.png"))); // NOI18N
        jLabel23.setMaximumSize(new java.awt.Dimension(32, 32));
        jLabel23.setMinimumSize(new java.awt.Dimension(32, 32));
        jLabel23.setName(""); // NOI18N
        jLabel23.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jLabel23.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel23MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelMenuLayout = new javax.swing.GroupLayout(panelMenu);
        panelMenu.setLayout(panelMenuLayout);
        panelMenuLayout.setHorizontalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelMenuLayout.setVerticalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuLayout.createSequentialGroup()
                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 10, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addComponent(panelMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addComponent(panelMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 12, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout panelIconoMenuLayout = new javax.swing.GroupLayout(panelIconoMenu);
        panelIconoMenu.setLayout(panelIconoMenuLayout);
        panelIconoMenuLayout.setHorizontalGroup(
            panelIconoMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelIconoMenuLayout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelIconoMenuLayout.setVerticalGroup(
            panelIconoMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelIconoMenuLayout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelMenuMinimizado.setBackground(new java.awt.Color(255, 255, 255));
        org.jdesktop.swingx.border.DropShadowBorder dropShadowBorder3 = new org.jdesktop.swingx.border.DropShadowBorder();
        dropShadowBorder3.setShadowSize(10);
        panelMenuMinimizado.setBorder(dropShadowBorder3);

        jPanel3.setBackground(new java.awt.Color(94, 94, 95));

        btnInicioXs.setBackground(new java.awt.Color(94, 94, 95));
        btnInicioXs.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        btnInicioXs.setPreferredSize(new java.awt.Dimension(53, 40));
        btnInicioXs.setRippleColor(new java.awt.Color(51, 204, 0));
        btnInicioXs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnInicioXsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnInicioXsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnInicioXsMouseExited(evt);
            }
        });

        jLabel27.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 12)); // NOI18N
        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/images/icons8_Home_24px_2.png"))); // NOI18N
        jLabel27.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jLabel27.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel27MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout btnInicioXsLayout = new javax.swing.GroupLayout(btnInicioXs);
        btnInicioXs.setLayout(btnInicioXsLayout);
        btnInicioXsLayout.setHorizontalGroup(
            btnInicioXsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnInicioXsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btnInicioXsLayout.setVerticalGroup(
            btnInicioXsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnInicioXsLayout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(jLabel27)
                .addContainerGap())
        );

        btnMadalineLg1.setBackground(new java.awt.Color(94, 94, 95));
        btnMadalineLg1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        btnMadalineLg1.setPreferredSize(new java.awt.Dimension(53, 40));
        btnMadalineLg1.setRippleColor(new java.awt.Color(51, 204, 0));
        btnMadalineLg1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMadalineLg1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMadalineLg1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMadalineLg1MouseExited(evt);
            }
        });

        jLabel28.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/images/icons8_Brain_24px.png"))); // NOI18N
        jLabel28.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout btnMadalineLg1Layout = new javax.swing.GroupLayout(btnMadalineLg1);
        btnMadalineLg1.setLayout(btnMadalineLg1Layout);
        btnMadalineLg1Layout.setHorizontalGroup(
            btnMadalineLg1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnMadalineLg1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel28, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE))
        );
        btnMadalineLg1Layout.setVerticalGroup(
            btnMadalineLg1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnMadalineLg1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jLabel28)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        btnPerceptronLg1.setBackground(new java.awt.Color(94, 94, 95));
        btnPerceptronLg1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        btnPerceptronLg1.setPreferredSize(new java.awt.Dimension(53, 40));
        btnPerceptronLg1.setRippleColor(new java.awt.Color(51, 204, 0));
        btnPerceptronLg1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPerceptronLg1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnPerceptronLg1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnPerceptronLg1MouseExited(evt);
            }
        });

        jLabel43.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 12)); // NOI18N
        jLabel43.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/images/icons8_Google_Scholar_24px_2.png"))); // NOI18N
        jLabel43.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout btnPerceptronLg1Layout = new javax.swing.GroupLayout(btnPerceptronLg1);
        btnPerceptronLg1.setLayout(btnPerceptronLg1Layout);
        btnPerceptronLg1Layout.setHorizontalGroup(
            btnPerceptronLg1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnPerceptronLg1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel43, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btnPerceptronLg1Layout.setVerticalGroup(
            btnPerceptronLg1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnPerceptronLg1Layout.createSequentialGroup()
                .addComponent(jLabel43)
                .addGap(0, 12, Short.MAX_VALUE))
        );

        btnSimularLg1.setBackground(new java.awt.Color(94, 94, 95));
        btnSimularLg1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        btnSimularLg1.setPreferredSize(new java.awt.Dimension(53, 40));
        btnSimularLg1.setRippleColor(new java.awt.Color(51, 204, 0));
        btnSimularLg1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSimularLg1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSimularLg1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSimularLg1MouseExited(evt);
            }
        });

        jLabel33.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 12)); // NOI18N
        jLabel33.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/images/icons8_HIPS_24px_2.png"))); // NOI18N
        jLabel33.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout btnSimularLg1Layout = new javax.swing.GroupLayout(btnSimularLg1);
        btnSimularLg1.setLayout(btnSimularLg1Layout);
        btnSimularLg1Layout.setHorizontalGroup(
            btnSimularLg1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnSimularLg1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel33)
                .addGap(60, 60, 60))
        );
        btnSimularLg1Layout.setVerticalGroup(
            btnSimularLg1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnSimularLg1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jLabel33)
                .addGap(20, 20, 20))
        );

        btnCrearLg1.setBackground(new java.awt.Color(94, 94, 95));
        btnCrearLg1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        btnCrearLg1.setPreferredSize(new java.awt.Dimension(53, 40));
        btnCrearLg1.setRippleColor(new java.awt.Color(51, 204, 0));
        btnCrearLg1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCrearLg1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCrearLg1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCrearLg1MouseExited(evt);
            }
        });

        jLabel35.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 12)); // NOI18N
        jLabel35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/images/icons8_Edit_Property_24px.png"))); // NOI18N
        jLabel35.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout btnCrearLg1Layout = new javax.swing.GroupLayout(btnCrearLg1);
        btnCrearLg1.setLayout(btnCrearLg1Layout);
        btnCrearLg1Layout.setHorizontalGroup(
            btnCrearLg1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnCrearLg1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel35)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        btnCrearLg1Layout.setVerticalGroup(
            btnCrearLg1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnCrearLg1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jLabel35)
                .addContainerGap())
        );

        btnVerRegistrosLg1.setBackground(new java.awt.Color(94, 94, 95));
        btnVerRegistrosLg1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        btnVerRegistrosLg1.setPreferredSize(new java.awt.Dimension(53, 40));
        btnVerRegistrosLg1.setRippleColor(new java.awt.Color(51, 204, 0));
        btnVerRegistrosLg1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVerRegistrosLg1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnVerRegistrosLg1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnVerRegistrosLg1MouseExited(evt);
            }
        });

        jLabel44.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 12)); // NOI18N
        jLabel44.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/images/icons8_Search_Property_24px_1.png"))); // NOI18N
        jLabel44.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout btnVerRegistrosLg1Layout = new javax.swing.GroupLayout(btnVerRegistrosLg1);
        btnVerRegistrosLg1.setLayout(btnVerRegistrosLg1Layout);
        btnVerRegistrosLg1Layout.setHorizontalGroup(
            btnVerRegistrosLg1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnVerRegistrosLg1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel44, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE))
        );
        btnVerRegistrosLg1Layout.setVerticalGroup(
            btnVerRegistrosLg1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnVerRegistrosLg1Layout.createSequentialGroup()
                .addComponent(jLabel44)
                .addGap(0, 12, Short.MAX_VALUE))
        );

        btnSalirLg1.setBackground(new java.awt.Color(94, 94, 95));
        btnSalirLg1.setPreferredSize(new java.awt.Dimension(53, 43));
        btnSalirLg1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSalirLg1MouseClicked(evt);
            }
        });

        jLabel45.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/images/icons8_Exit_Sign_24px_3.png"))); // NOI18N

        javax.swing.GroupLayout btnSalirLg1Layout = new javax.swing.GroupLayout(btnSalirLg1);
        btnSalirLg1.setLayout(btnSalirLg1Layout);
        btnSalirLg1Layout.setHorizontalGroup(
            btnSalirLg1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnSalirLg1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel45, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(19, 19, 19))
        );
        btnSalirLg1Layout.setVerticalGroup(
            btnSalirLg1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnSalirLg1Layout.createSequentialGroup()
                .addComponent(jLabel45, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnPerceptronLg1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btnSimularLg1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btnCrearLg1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btnMadalineLg1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btnInicioXs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btnVerRegistrosLg1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btnSalirLg1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(btnInicioXs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnMadalineLg1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnPerceptronLg1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnSimularLg1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnCrearLg1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnVerRegistrosLg1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(btnSalirLg1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout panelMenuMinimizadoLayout = new javax.swing.GroupLayout(panelMenuMinimizado);
        panelMenuMinimizado.setLayout(panelMenuMinimizadoLayout);
        panelMenuMinimizadoLayout.setHorizontalGroup(
            panelMenuMinimizadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuMinimizadoLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelMenuMinimizadoLayout.setVerticalGroup(
            panelMenuMinimizadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        panelCardLayout.setBackground(new java.awt.Color(255, 255, 255));
        org.jdesktop.swingx.border.DropShadowBorder dropShadowBorder4 = new org.jdesktop.swingx.border.DropShadowBorder();
        dropShadowBorder4.setShowLeftShadow(true);
        dropShadowBorder4.setShowTopShadow(true);
        panelCardLayout.setBorder(dropShadowBorder4);

        panelContenido.setBackground(new java.awt.Color(255, 255, 255));
        panelContenido.setLayout(new java.awt.CardLayout());

        panelSimulacionPersonalizada.setBackground(new java.awt.Color(255, 255, 255));

        panelEntradasSimulacion.setBackground(new java.awt.Color(255, 255, 255));
        org.jdesktop.swingx.border.DropShadowBorder dropShadowBorder5 = new org.jdesktop.swingx.border.DropShadowBorder();
        dropShadowBorder5.setShowLeftShadow(true);
        dropShadowBorder5.setShowTopShadow(true);
        panelEntradasSimulacion.setBorder(dropShadowBorder5);
        panelEntradasSimulacion.setPreferredSize(new java.awt.Dimension(390, 271));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        org.jdesktop.swingx.border.DropShadowBorder dropShadowBorder6 = new org.jdesktop.swingx.border.DropShadowBorder();
        dropShadowBorder6.setShowRightShadow(false);
        jPanel4.setBorder(dropShadowBorder6);

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        jLabel3.setText("Entradas de la red");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        org.jdesktop.swingx.border.DropShadowBorder dropShadowBorder7 = new org.jdesktop.swingx.border.DropShadowBorder();
        dropShadowBorder7.setShowBottomShadow(false);
        dropShadowBorder7.setShowRightShadow(false);
        dropShadowBorder7.setShowTopShadow(true);
        jPanel7.setBorder(dropShadowBorder7);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 15, Short.MAX_VALUE)
        );

        jScrollPane4.setBorder(null);

        textAreaEntradas.setColumns(20);
        textAreaEntradas.setLineWrap(true);
        textAreaEntradas.setRows(2);
        textAreaEntradas.setTabSize(4);
        textAreaEntradas.setToolTipText("Digita las Entradas Separadas Por espacio");
        textAreaEntradas.setAutoscrolls(false);
        textAreaEntradas.setBorder(null);
        jScrollPane4.setViewportView(textAreaEntradas);

        btnSimulacionPersonalizada1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSimulacionPersonalizada1MouseClicked(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 11)); // NOI18N
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/images/icons8_Play_24px.png"))); // NOI18N
        jLabel7.setText("Simular");

        javax.swing.GroupLayout btnSimulacionPersonalizada1Layout = new javax.swing.GroupLayout(btnSimulacionPersonalizada1);
        btnSimulacionPersonalizada1.setLayout(btnSimulacionPersonalizada1Layout);
        btnSimulacionPersonalizada1Layout.setHorizontalGroup(
            btnSimulacionPersonalizada1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnSimulacionPersonalizada1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addContainerGap(28, Short.MAX_VALUE))
        );
        btnSimulacionPersonalizada1Layout.setVerticalGroup(
            btnSimulacionPersonalizada1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnSimulacionPersonalizada1Layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        textAreaSalidas.setColumns(20);
        textAreaSalidas.setLineWrap(true);
        textAreaSalidas.setRows(5);
        textAreaSalidas.setWrapStyleWord(true);
        jScrollPane5.setViewportView(textAreaSalidas);

        javax.swing.GroupLayout panelEntradasSimulacionLayout = new javax.swing.GroupLayout(panelEntradasSimulacion);
        panelEntradasSimulacion.setLayout(panelEntradasSimulacionLayout);
        panelEntradasSimulacionLayout.setHorizontalGroup(
            panelEntradasSimulacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelEntradasSimulacionLayout.createSequentialGroup()
                .addContainerGap(183, Short.MAX_VALUE)
                .addComponent(btnSimulacionPersonalizada1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(209, 209, 209))
            .addGroup(panelEntradasSimulacionLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(panelEntradasSimulacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 434, Short.MAX_VALUE)
                    .addGroup(panelEntradasSimulacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 434, Short.MAX_VALUE)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panelEntradasSimulacionLayout.setVerticalGroup(
            panelEntradasSimulacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEntradasSimulacionLayout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSimulacionPersonalizada1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        GraficaPersonalizada.setBackground(new java.awt.Color(255, 255, 255));
        GraficaPersonalizada.setPreferredSize(new java.awt.Dimension(281, 271));

        javax.swing.GroupLayout GraficaPersonalizadaLayout = new javax.swing.GroupLayout(GraficaPersonalizada);
        GraficaPersonalizada.setLayout(GraficaPersonalizadaLayout);
        GraficaPersonalizadaLayout.setHorizontalGroup(
            GraficaPersonalizadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 231, Short.MAX_VALUE)
        );
        GraficaPersonalizadaLayout.setVerticalGroup(
            GraficaPersonalizadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 368, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelSimulacionPersonalizadaLayout = new javax.swing.GroupLayout(panelSimulacionPersonalizada);
        panelSimulacionPersonalizada.setLayout(panelSimulacionPersonalizadaLayout);
        panelSimulacionPersonalizadaLayout.setHorizontalGroup(
            panelSimulacionPersonalizadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSimulacionPersonalizadaLayout.createSequentialGroup()
                .addComponent(panelEntradasSimulacion, javax.swing.GroupLayout.DEFAULT_SIZE, 510, Short.MAX_VALUE)
                .addGap(31, 31, 31)
                .addComponent(GraficaPersonalizada, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE))
        );
        panelSimulacionPersonalizadaLayout.setVerticalGroup(
            panelSimulacionPersonalizadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSimulacionPersonalizadaLayout.createSequentialGroup()
                .addGroup(panelSimulacionPersonalizadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelEntradasSimulacion, javax.swing.GroupLayout.DEFAULT_SIZE, 368, Short.MAX_VALUE)
                    .addComponent(GraficaPersonalizada, javax.swing.GroupLayout.DEFAULT_SIZE, 368, Short.MAX_VALUE))
                .addContainerGap())
        );

        panelContenido.add(panelSimulacionPersonalizada, "card2");

        panelSimulacionGeneral.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        org.jdesktop.swingx.border.DropShadowBorder dropShadowBorder8 = new org.jdesktop.swingx.border.DropShadowBorder();
        dropShadowBorder8.setShowRightShadow(false);
        jPanel8.setBorder(dropShadowBorder8);

        jLabel5.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 12)); // NOI18N
        jLabel5.setText("Datos Participes del Entrenamiento");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addContainerGap(65, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(jLabel5)
                .addGap(0, 11, Short.MAX_VALUE))
        );

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tabla);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 317, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelGraficaGeneralzada.setBackground(new java.awt.Color(255, 255, 255));
        panelGraficaGeneralzada.setPreferredSize(new java.awt.Dimension(415, 271));

        javax.swing.GroupLayout panelGraficaGeneralzadaLayout = new javax.swing.GroupLayout(panelGraficaGeneralzada);
        panelGraficaGeneralzada.setLayout(panelGraficaGeneralzadaLayout);
        panelGraficaGeneralzadaLayout.setHorizontalGroup(
            panelGraficaGeneralzadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 453, Short.MAX_VALUE)
        );
        panelGraficaGeneralzadaLayout.setVerticalGroup(
            panelGraficaGeneralzadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelSimulacionGeneralLayout = new javax.swing.GroupLayout(panelSimulacionGeneral);
        panelSimulacionGeneral.setLayout(panelSimulacionGeneralLayout);
        panelSimulacionGeneralLayout.setHorizontalGroup(
            panelSimulacionGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSimulacionGeneralLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelGraficaGeneralzada, javax.swing.GroupLayout.DEFAULT_SIZE, 453, Short.MAX_VALUE))
        );
        panelSimulacionGeneralLayout.setVerticalGroup(
            panelSimulacionGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelGraficaGeneralzada, javax.swing.GroupLayout.DEFAULT_SIZE, 379, Short.MAX_VALUE)
        );

        panelContenido.add(panelSimulacionGeneral, "card3");

        cbxNombreRed.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 14)); // NOI18N
        cbxNombreRed.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "nombre" }));
        cbxNombreRed.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxNombreRedItemStateChanged(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        jLabel2.setText("Eleccion de red");

        buttonGroup1.add(rdoSupervisadas);
        rdoSupervisadas.setSelected(true);
        rdoSupervisadas.setText("Supervisadas");

        buttonGroup1.add(rdoBasesRadiales);
        rdoBasesRadiales.setText("Bases Radiales");

        buttonGroup1.add(rdoNosupervisadas);
        rdoNosupervisadas.setText("No supervisada");
        rdoNosupervisadas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoNosupervisadasActionPerformed(evt);
            }
        });

        panelTipoSimulacion.setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 11)); // NOI18N
        jLabel4.setText("Generalizada ");

        switchTipoSimulacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                switchTipoSimulacionMouseClicked(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 11)); // NOI18N
        jLabel6.setText("Personalizada");

        jLabel8.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        jLabel8.setText("Tipo de simulacion");

        javax.swing.GroupLayout panelTipoSimulacionLayout = new javax.swing.GroupLayout(panelTipoSimulacion);
        panelTipoSimulacion.setLayout(panelTipoSimulacionLayout);
        panelTipoSimulacionLayout.setHorizontalGroup(
            panelTipoSimulacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTipoSimulacionLayout.createSequentialGroup()
                .addGroup(panelTipoSimulacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelTipoSimulacionLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(switchTipoSimulacion, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4))
                    .addGroup(panelTipoSimulacionLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jLabel8)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelTipoSimulacionLayout.setVerticalGroup(
            panelTipoSimulacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTipoSimulacionLayout.createSequentialGroup()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelTipoSimulacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(switchTipoSimulacion, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6))
                .addContainerGap())
        );

        javax.swing.GroupLayout panelCardLayoutLayout = new javax.swing.GroupLayout(panelCardLayout);
        panelCardLayout.setLayout(panelCardLayoutLayout);
        panelCardLayoutLayout.setHorizontalGroup(
            panelCardLayoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCardLayoutLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(panelCardLayoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelContenido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelCardLayoutLayout.createSequentialGroup()
                        .addGroup(panelCardLayoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panelTipoSimulacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelCardLayoutLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(cbxNombreRed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(136, 136, 136)
                                .addComponent(rdoSupervisadas)
                                .addGap(18, 18, 18)
                                .addComponent(rdoBasesRadiales)
                                .addGap(18, 18, 18)
                                .addComponent(rdoNosupervisadas)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelCardLayoutLayout.setVerticalGroup(
            panelCardLayoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCardLayoutLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(panelCardLayoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rdoSupervisadas)
                    .addComponent(rdoBasesRadiales)
                    .addComponent(rdoNosupervisadas)
                    .addComponent(cbxNombreRed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelTipoSimulacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelContenido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(26, 26, 26))
        );

        javax.swing.GroupLayout panelCuerpoLayout = new javax.swing.GroupLayout(panelCuerpo);
        panelCuerpo.setLayout(panelCuerpoLayout);
        panelCuerpoLayout.setHorizontalGroup(
            panelCuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(paneTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelCuerpoLayout.createSequentialGroup()
                .addGroup(panelCuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelIconoMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelMenuMinimizado, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(panelCardLayout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelCuerpoLayout.setVerticalGroup(
            panelCuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCuerpoLayout.createSequentialGroup()
                .addComponent(paneTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addGroup(panelCuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCuerpoLayout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(panelIconoMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(panelMenuMinimizado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelCuerpoLayout.createSequentialGroup()
                        .addComponent(panelCardLayout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelCuerpo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelCuerpo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInicioXsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInicioXsMouseClicked
        // TODO add your handling code here:
        new FrmInicio().setVisible(true);
    }//GEN-LAST:event_btnInicioXsMouseClicked

    private void btnInicioXsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInicioXsMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnInicioXsMouseEntered

    private void btnInicioXsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInicioXsMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnInicioXsMouseExited

    private void btnMadalineLg1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMadalineLg1MouseClicked
        // TODO add your handling code here:
        new FrmSimular().setVisible(true);
    }//GEN-LAST:event_btnMadalineLg1MouseClicked

    private void btnMadalineLg1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMadalineLg1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMadalineLg1MouseEntered

    private void btnMadalineLg1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMadalineLg1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMadalineLg1MouseExited

    private void btnPerceptronLg1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPerceptronLg1MouseClicked
        // TODO add your handling code here:
        new FrmPerceptron().setVisible(true);
    }//GEN-LAST:event_btnPerceptronLg1MouseClicked

    private void btnPerceptronLg1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPerceptronLg1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPerceptronLg1MouseEntered

    private void btnPerceptronLg1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPerceptronLg1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPerceptronLg1MouseExited

    private void btnSimularLg1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSimularLg1MouseClicked
        // TODO add your handling code here:
        new FrmSimular().setVisible(true);
    }//GEN-LAST:event_btnSimularLg1MouseClicked

    private void btnSimularLg1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSimularLg1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSimularLg1MouseEntered

    private void btnSimularLg1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSimularLg1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSimularLg1MouseExited

    private void btnCrearLg1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCrearLg1MouseClicked
        // TODO add your handling code here:
        new FrmCrearArchivo().setVisible(true);
    }//GEN-LAST:event_btnCrearLg1MouseClicked

    private void btnCrearLg1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCrearLg1MouseEntered
        // TODO add your handling code here:

    }//GEN-LAST:event_btnCrearLg1MouseEntered

    private void btnCrearLg1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCrearLg1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCrearLg1MouseExited

    private void btnVerRegistrosLg1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVerRegistrosLg1MouseClicked
        // TODO add your handling code here:
        new FrmConsultarArchivos().setVisible(true);
    }//GEN-LAST:event_btnVerRegistrosLg1MouseClicked

    private void btnVerRegistrosLg1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVerRegistrosLg1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVerRegistrosLg1MouseEntered

    private void btnVerRegistrosLg1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVerRegistrosLg1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVerRegistrosLg1MouseExited

    private void btnSalirLg1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirLg1MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnSalirLg1MouseClicked

    private void jLabel27MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel27MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel27MouseClicked

    private void jLabel23MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel23MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel23MouseClicked

    private void panelMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelMenuMouseClicked
        // TODO add your handling code here:
        int posicion = panelMenuMinimizado.getX();
        if (posicion > -1) {
            Animacion.Animacion.mover_izquierda(0, -264, 2, 2, panelMenuMinimizado);
        } else {
            Animacion.Animacion.mover_derecha(-264, 0, 2, 2, panelMenuMinimizado);
        }
    }//GEN-LAST:event_panelMenuMouseClicked

    private void formMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseMoved
        // TODO add your handling code here:
        if (rootPaneCheckingEnabled) {

        }
    }//GEN-LAST:event_formMouseMoved

    private void cbxNombreRedItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxNombreRedItemStateChanged
        // TODO add your handling code here:
        if (!cbxNombreRed.getSelectedItem().equals("nombre")) {
            gspu = new getSetPesosUmbrales((String) cbxNombreRed.getSelectedItem());
            gspu.leerPesosUmbrales();
            //maquetarEntradas();
            textAreaEntradas.removeAll();
            textAreaSalidas.removeAll();
            textAreaEntradas.setText("");
            textAreaSalidas.setText("");
            panelTipoSimulacion.setVisible(true);
            panelContenido.setVisible(true);
        } else {
            panelContenido.setVisible(false);
            panelTipoSimulacion.setVisible(false);
        }

    }//GEN-LAST:event_cbxNombreRedItemStateChanged

    private void btnSimulacionPersonalizada1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSimulacionPersonalizada1MouseClicked
        // TODO add your handling code here:
        simulacionPersonalizada();
        //textAreaSalidas.removeAll();
        //textAreaSalidas.setText("");

    }//GEN-LAST:event_btnSimulacionPersonalizada1MouseClicked

    private void rdoNosupervisadasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoNosupervisadasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdoNosupervisadasActionPerformed

    private void switchTipoSimulacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_switchTipoSimulacionMouseClicked
        // TODO add your handling code here:
        //switchTipoSimulacion
        if (switchTipoSimulacion.isOnOff()) {
            CardLayout cardLayout = (CardLayout) panelContenido.getLayout();
            cardLayout.show(panelContenido, "card2");
        } else {
            CardLayout cardLayout = (CardLayout) panelContenido.getLayout();
            cardLayout.show(panelContenido, "card3");
            graficarGeneral("Grafica General");
        }
    }//GEN-LAST:event_switchTipoSimulacionMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmSimular.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmSimular.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmSimular.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmSimular.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmSimular().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel GraficaPersonalizada;
    private MaterialSwing.MaterialButtomPanel btnCrearLg1;
    private MaterialSwing.MaterialButtomPanel btnInicioXs;
    private MaterialSwing.MaterialButtomPanel btnMadalineLg1;
    private MaterialSwing.MaterialButtomPanel btnPerceptronLg1;
    private MaterialSwing.MaterialButtomPanel btnSalirLg1;
    private MaterialSwing.MaterialButtomPanel btnSimulacionPersonalizada1;
    private MaterialSwing.MaterialButtomPanel btnSimularLg1;
    private MaterialSwing.MaterialButtomPanel btnVerRegistrosLg1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbxNombreRed;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel paneTitulo;
    private javax.swing.JPanel panelCardLayout;
    private javax.swing.JPanel panelContenido;
    private javax.swing.JPanel panelCuerpo;
    private javax.swing.JPanel panelEntradasSimulacion;
    private javax.swing.JPanel panelGraficaGeneralzada;
    private javax.swing.JPanel panelIconoMenu;
    private MaterialSwing.MaterialButtomPanel panelMenu;
    private javax.swing.JPanel panelMenuMinimizado;
    private javax.swing.JPanel panelSimulacionGeneral;
    private javax.swing.JPanel panelSimulacionPersonalizada;
    private javax.swing.JPanel panelTipoSimulacion;
    private javax.swing.JRadioButton rdoBasesRadiales;
    private javax.swing.JRadioButton rdoNosupervisadas;
    private javax.swing.JRadioButton rdoSupervisadas;
    private MaterialSwing.MaterialSwitch switchTipoSimulacion;
    private javax.swing.JTable tabla;
    private javax.swing.JTextArea textAreaEntradas;
    private javax.swing.JTextArea textAreaSalidas;
    // End of variables declaration//GEN-END:variables

    public void setColor(JPanel panel) {
        /*contentPane.setBackground(new java.awt.Color(255, 255, 255));
        contentPane.setBorder(BorderFactory.createLineBorder(Color.WHITE));*/
    }

    public void resetColor(JPanel panel) {
        /* contentPane.setBackground(new java.awt.Color(204, 204, 204));*/
    }

    public static void setEnableContainer(Container c, boolean band) {

        Component[] components = c.getComponents();
        c.setEnabled(band);
        for (int i = 0; i < components.length; i++) {
            components[i].setEnabled(band);

            if (components[i] instanceof Container) {
                setEnableContainer((Container) components[i], band);
            }

        }

    }

    public void listarArchivos() {
        String sDirectorio = System.getProperty("user.dir") + "\\RedesNeuronales";
        File f = new File(sDirectorio);
        if (f.exists()) { // Directorio existe 
            File[] ficheros = f.listFiles();
            for (int x = 0; x < ficheros.length; x++) {
                cbxNombreRed.addItem(ficheros[x].getName());
            }
        }
    }
    private static final long serialVersionUID = 1L;

    /**
     * Creates a sample dataset
     */
    private DefaultCategoryDataset createDataset() {
        DefaultCategoryDataset result = new DefaultCategoryDataset();
        String[] salida = new String[gspu.getN()];
        result.setValue(0, "Yd", "patron1");
        result.setValue(0, "Yr", "patron1");

        result.setValue(0, "Yd", "patron2");
        result.setValue(0, "Yr", "patron2");

        return result;

    }

    /**
     * Creates a chart por andres2288
     */
    private JFreeChart createChart(DefaultCategoryDataset dataset, String title) {

        JFreeChart chart = ChartFactory.createBarChart3D(title, "Salidas",
                "valores", dataset, // data
                PlotOrientation.VERTICAL, true, // include legend
                true, false);
        CategoryPlot plot = (CategoryPlot) chart.getPlot();
        CategoryAxis xAxis = (CategoryAxis) plot.getDomainAxis();
        xAxis.setCategoryLabelPositions(CategoryLabelPositions.UP_45); // Inclinamos 45 grados las etiquetas del eje X
        plot.setBackgroundAlpha(0.5f);

        //personalización del grafico color de fondo 
        plot.setBackgroundPaint(Color.white);
        //personalización del grafico color de los grit 
        plot.setDomainGridlinePaint(Color.BLACK);
        plot.setRangeGridlinePaint(Color.BLACK);
        // disable bar outlines...
        BarRenderer renderer = (BarRenderer) plot.getRenderer();
        renderer.setDrawBarOutline(false);
        // set up gradient paints for series...
        GradientPaint gp0 = new GradientPaint(
                0.0f, 0.0f, Color.green,
                0.0f, 0.0f, new Color(0, 0, 64)
        );
        GradientPaint gp1 = new GradientPaint(
                0.0f, 0.0f, Color.blue,
                0.0f, 0.0f, new Color(0, 64, 0)
        );
        GradientPaint gp2 = new GradientPaint(
                0.0f, 0.0f, Color.red,
                0.0f, 0.0f, new Color(64, 0, 0)
        );
        renderer.setSeriesPaint(0, gp0);
        renderer.setSeriesPaint(1, gp1);
        renderer.setSeriesPaint(2, gp2);

        return chart;
    }

    private void graficarGeneral(String chartTitle) {
        

        tabla.setVisible(true);
        int fil = gspu.getPatrones();
        int col = gspu.getM() + gspu.getN();

        String tituloTabla[] = new String[col];
        for (int i = 0; i < gspu.getM(); i++) {
            tituloTabla[i] = "X" + (i + 1);
        }
        for (int i = 0; i < gspu.getN(); i++) {
            tituloTabla[i + gspu.getM()] = "Y" + (i + 1);
        }

        Class[] tipoTabla = new Class[col];
        for (int i = 0; i < col; i++) {
            tipoTabla[i] = java.lang.Double.class;
        }

        Object obTabla[][] = new Object[fil][col];

        for (int i = 0; i < fil; i++) {
            for (int j = 0; j < col; j++) {
                obTabla[i][j] = 0;
            }
            for (int j = 0; j < gspu.getX()[i].length; j++) {
                obTabla[i][j] = gspu.getX()[i][j];
            }
            for (int j = 0; j < gspu.getY()[i].length; j++) {
                obTabla[i][j + gspu.getX()[i].length] = gspu.getY()[i][j];
            }
        }

        tabla.setModel(new javax.swing.table.DefaultTableModel(
                obTabla,
                tituloTabla) {
            Class[] types = tipoTabla;

            public Class getColumnClass(int columnIndex) {
                return types[columnIndex];
            }
        });
        //tabla.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        tabla.setColumnSelectionAllowed(true);
        tabla.getTableHeader().setReorderingAllowed(false);
//        jScrollPane1.setViewportView(tabla);
//        jScrollPane1.setBounds(20, 80, col*83, fil*24);
        tabla.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        
        DefaultCategoryDataset dataset = createDataset();
        double[] yr = new double[gspu.getY()[0].length];
        for (int i = 0; i < gspu.getPatrones(); i++) {
            yr = simular(gspu.getX()[i]);
            for (int j = 0; j < gspu.getY()[i].length; j++) {
                dataset.setValue(gspu.getY()[i][j], "Yd", "patron" + (i + 1));
                dataset.setValue(yr[j], "Yr", "patron" + (i + 1));
            }
        }

        JFreeChart chart = createChart(dataset, chartTitle);

        // Ponemos el gráfico en un contentPane
        ChartPanel chartPanel = new ChartPanel(chart);
        // Dejamos el tamaño por defecto
        chartPanel.setPreferredSize(new java.awt.Dimension(500, 270));

        chartPanel.setBounds(30, 300, 700, 200);
        panelGraficaGeneralzada.removeAll();
        panelGraficaGeneralzada.setLayout(new java.awt.BorderLayout());
        panelGraficaGeneralzada.add(chartPanel);
        panelGraficaGeneralzada.validate();
    }

    private void graficarIndividual(String chartTitle, double[] x, double[] yr) {
        DefaultCategoryDataset dataset = new DefaultCategoryDataset();

        if (x == null) {
            for (int i = 0; i < gspu.getN(); i++) {
                dataset.setValue(0, "Yd", "Salidas");
                dataset.setValue(0, "Yr", "Salidas");
            }
        } else {
            double[] yd = new double[gspu.getN()];
            int posX = 0;
            boolean esta = false;
            for (int i = 0; i < gspu.getX().length; i++) {
                for (int j = 0; j < gspu.getX()[i].length; j++) {
                    esta = gspu.getX()[i][j] == x[j];
                    if (!esta) {
                        break;
                    }
                }
                if (esta) {
                    posX = i;
                    break;
                }
            }
            if (!esta) {
                JOptionPane.showMessageDialog(null, "el patron no participo en el entrenamiento", "Precausion", JOptionPane.WARNING_MESSAGE);
            }
            yd = gspu.getY()[posX];
            for (int i = 0; i < gspu.getN(); i++) {
                dataset.setValue(yd[i], "Yd", "Salidas");
                dataset.setValue(yr[i], "Yr", "Salidas");
            }
        }
        JFreeChart chart = createChart(dataset, chartTitle);

        // Ponemos el gráfico en un contentPane
        ChartPanel chartPanel = new ChartPanel(chart);
        // Dejamos el tamaño por defecto
        chartPanel.setPreferredSize(new java.awt.Dimension(500, 270));

        chartPanel.setBounds(30, 300, 700, 200);
        GraficaPersonalizada.removeAll();
        GraficaPersonalizada.setLayout(new java.awt.BorderLayout());
        GraficaPersonalizada.add(chartPanel);
        GraficaPersonalizada.validate();

    }

    JPanel panelSalidas = new JPanel(new GridLayout(0, 4, 5, 5));
    JPanel PanelEntradas = new JPanel(new FlowLayout());

    /*private void maquetarEntradas() {

        graficarIndividual("Grafica", null, null);
        JPanel panelSimulacionCentral = new JPanel(new BorderLayout());
        JPanel gui = new JPanel(new BorderLayout(2, 2));
        JPanel labelFields = new JPanel(new BorderLayout(2, 2));
        labelFields.setBorder(BorderFactory.createLineBorder(Color.WHITE));
        PanelEntradas.removeAll();
        PanelEntradas.setBorder(new TitledBorder(""));
        PanelEntradas.setBackground(Color.WHITE);
        
        MaterialTextField textField = new MaterialTextField();
        textField.setPreferredSize(new Dimension(PanelEntradas.getWidth()-5, PanelEntradas.getHeight()-5));
        PanelEntradas.add(textField);

        PanelEntradas.setBorder(BorderFactory.createMatteBorder(1, 1, 1, 1, Color.WHITE));
        JPanel panelAux = new JPanel(new FlowLayout());
        panelAux.setBackground(Color.WHITE);
        panelAux.setBorder(BorderFactory.createLineBorder(Color.WHITE));
        panelAux.add(PanelEntradas);
        JScrollPane jsc = new JScrollPane(panelAux);
        jsc.setBorder(BorderFactory.createLineBorder(Color.WHITE));
        JPanel panelm = new JPanel(new FlowLayout(FlowLayout.LEFT));
        panelm.add(new JLabel("  Entradas de la red."));
        panelm.setBackground(Color.WHITE);
        DropShadowBorder dropShadowBorder1 = new DropShadowBorder();
        dropShadowBorder1.setShowBottomShadow(true);
        dropShadowBorder1.setShowRightShadow(false);
        dropShadowBorder1.setShowLeftShadow(false);
        panelm.setBorder(dropShadowBorder1);
        labelFields.add(panelm, BorderLayout.PAGE_START);
        labelFields.add(jsc, BorderLayout.CENTER);
        labelFields.setSize(390, 100);
        labelFields.setBackground(Color.WHITE);
        labelFields.setPreferredSize(new Dimension(390, 100));
        labelFields.setBorder(BorderFactory.createLineBorder(Color.WHITE));

        JPanel buttonConstrain = new JPanel(new FlowLayout(FlowLayout.CENTER));
        buttonConstrain.setBackground(Color.WHITE);
        DropShadowBorder dropShadowBorder5 = new DropShadowBorder();
        dropShadowBorder5.setShowBottomShadow(true);
        dropShadowBorder5.setShowRightShadow(false);
        dropShadowBorder5.setShowTopShadow(true);
        //buttonConstrain.setBorder(dropShadowBorder5);
        // buttonConstrain.setBorder(new TitledBorder(""));
        buttonConstrain.setBorder(dropShadowBorder5);
        MaterialButton boton1 = new MaterialButton();
        boton1.setText("Simular");
        boton1.setSize(100, 60);
        boton1.setPreferredSize(new Dimension(100, 40));
        boton1.setVisible(true);
        // Asignamos una Accion al JButton 
        boton1.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                simulacionPersonalizada();
            }
        });
        buttonConstrain.add(boton1);
        panelSimulacionCentral.add(buttonConstrain, BorderLayout.NORTH);
        panelSimulacionCentral.setBackground(Color.WHITE);
        panelSalidas.setBackground(Color.WHITE);
        panelSalidas.removeAll();
        panelSalidas.add(new JLabel("Esperando..."));
        panelSalidas.validate();
        panelSalidas.repaint();
        JPanel panelAuxS = new JPanel(new FlowLayout());
        panelAuxS.setBackground(Color.WHITE);
        panelAuxS.setBorder(BorderFactory.createLineBorder(Color.WHITE));
        panelAuxS.add(panelSalidas);
        JScrollPane jscs = new JScrollPane(panelAuxS);
        jscs.setBorder(BorderFactory.createLineBorder(Color.WHITE));

        panelSimulacionCentral.add(jscs);
        JPanel pn1 = new JPanel();
        pn1.setBackground(Color.WHITE);
        DropShadowBorder dsb = new DropShadowBorder();
        dsb.setShowBottomShadow(false);
        dsb.setShowRightShadow(false);
        dsb.setShowTopShadow(true);
        pn1.setBorder(dsb);
        gui.add(labelFields, BorderLayout.NORTH);
        gui.add(panelSimulacionCentral, BorderLayout.CENTER);
        gui.add(pn1, BorderLayout.SOUTH);
        gui.setBackground(Color.WHITE);
        //JOptionPane.showMessageDialog(null, gui);
        panelEntradasSimulacion.removeAll();
        panelEntradasSimulacion.setLayout(new BorderLayout());
        panelEntradasSimulacion.add(gui);
    }*/
    double[] simular(double[] x) {
        double[] yr = new double[gspu.getN()];
        //variables posibles para la simulacion
        switch (gspu.getCantCapa()) {
            case 1: {

                double[] h = new double[gspu.getO()];
                double[] s = new double[gspu.getO()];
                double[] ss = new double[gspu.getN()];
                //calcular salida capa oculta 1 "O"
                for (int i = 0; i < gspu.getO(); i++) {
                    s[i] = 0;
                    for (int j = 0; j < gspu.getM(); j++) {
                        s[i] = s[i] + x[j] * gspu.getW()[j][i];
                    }

                    s[i] = s[i] - gspu.getU()[i];
                    h[i] = gspu.activacion(gspu.getFuncionE(), (s[i]));

                }

                for (int i = 0; i < gspu.getN(); i++) {
                    ss[i] = 0;
                    for (int j = 0; j < gspu.getO(); j++) {
                        ss[i] = ss[i] + h[j] * gspu.getWs()[j][i];
                    }
                    ss[i] = ss[i] - gspu.getUs()[i];
                    yr[i] = gspu.activacion(gspu.getFuncionS(), (ss[i]));
                }
            }
            break;
            case 2: {

                double[] h = new double[gspu.getO()];
                double[] hc = new double[gspu.getÑ()];
                //calcular salida capa oculta 1 "O"
                double somao = 0;
                for (int i = 0; i < gspu.getO(); i++) {
                    for (int j = 0; j < gspu.getM(); j++) {
                        somao = somao + gspu.getW()[j][i] * x[j];
                    }
                    somao = somao - gspu.getU()[i];
                    h[i] = gspu.activacion(gspu.getFuncionE(), somao);
                    somao = 0;
                    //yo[i]=sigmoide(somao);
                }

                //calcular la salida capa oculta 2 "Ñ"
                double somañ = 0;
                for (int i = 0; i < gspu.getÑ(); i++) {

                    for (int j = 0; j < gspu.getO(); j++) {
                        somañ = somañ + gspu.getWc()[j][i] * h[j];
                    }
                    somañ = somañ - gspu.getUc()[i];
                    hc[i] = gspu.activacion(gspu.getFuncionC(), somañ);
                    //yñ[i]=sigmoide(somañ);
                }

                // calculamos la salida capa de salida "N"
                double soma = 0;

                for (int i = 0; i < gspu.getN(); i++) {
                    for (int j = 0; j < gspu.getÑ(); j++) {
                        soma = soma + gspu.getWs()[j][i] * hc[j];
                    }
                    soma = soma - gspu.getUs()[i];

                    //yr[i]=soma;
                    // System.out.println("función soma "+soma);
                    yr[i] = gspu.activacion(gspu.getFuncionS(), soma);
                    //yr[i]=gausiana(soma);
                    //System.out.println("ERROR LINEAL "+El[i
                }
            }
            break;
            case 3: {

            }

            break;
        }
        return yr;
    }

    private void simulacionPersonalizada() {
        int k = 0;
        double[] v = new double[gspu.getM()];
        boolean vacio = false;
        double[] yr = null;
        /* for (int l = 0; l < PanelEntradas.getComponentCount(); l++) {
            if (PanelEntradas.getComponent(l) instanceof MaterialTextField) {
                MaterialTextField textField = (MaterialTextField) PanelEntradas.getComponent(l);
                System.out.println(textField.getText());
                try {
                   entradas = textField.getText();
                } catch (NumberFormatException ex) {
                    vacio = true;
                }
                k++;
            }
        }*/
        if (vacio) {
            JOptionPane.showMessageDialog(null, "No has ingresado valor en alguna entrada", "Error Campos vacio", JOptionPane.ERROR_MESSAGE);
        } else {
            String[] vecE = textAreaEntradas.getText().split(" ");
            System.out.println("Vector De Entrada");
            for (int i = 0; i < vecE.length; i++) {
                v[i] = Double.parseDouble(vecE[i]);
                System.out.printf("V[%d]: %f", i, v[i]);

            }

            yr = simular(v);
        }
        // panelSalidas.removeAll();
        textAreaSalidas.setText("");
        for (int i = 0; i < gspu.getN(); i++) {
            //panelSalidas.add(new JLabel("salida " + i + ": "));
            //MaterialTextField txt = new MaterialTextField();
            //txt.setText("" + yr[i]);
            //panelSalidas.add(txt);
            //panelSalidas.add(Box.createHorizontalStrut(15)); // a spacer
            textAreaSalidas.append(String.format("y(%d) : %f \t", i, yr[i]));
        }
        //panelSalidas.validate();
        //panelSalidas.repaint();
        graficarIndividual("Grafica", v, yr);
    }
}
